// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c0012448be4e00327689c0c05e2f511411c9fc99a4fc8f44745d064434b738f2
fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    cbindgen::generate(crate_dir)
        .expect("Unable to generate C bindings")
        .write_to_file("include/kreuzberg.h");

    let go_include_dir = std::path::Path::new("../../../packages/go/v5/include");
    std::fs::create_dir_all(go_include_dir).expect("Unable to create Go include directory");
    std::fs::copy("include/kreuzberg.h", go_include_dir.join("kreuzberg.h"))
        .expect("Unable to copy header to Go include directory");
}
