# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: batch
defmodule E2e.BatchTest do
  use ExUnit.Case, async: false

  describe "batch_bytes_invalid_mime" do
    @tag :skip
    test "batch_bytes_invalid_mime" do
      # batch functions excluded from Elixir binding: unsafe NIF tuple marshalling
      :ok
    end
  end

  describe "batch_extract_bytes_happy" do
    @tag :skip
    test "batch_extract_bytes_happy" do
      # batch functions excluded from Elixir binding: unsafe NIF tuple marshalling
      :ok
    end
  end

  describe "batch_extract_bytes_mixed_format" do
    @tag :skip
    test "batch_extract_bytes_mixed_format" do
      # batch functions excluded from Elixir binding: unsafe NIF tuple marshalling
      :ok
    end
  end

  describe "batch_extract_bytes_sync_empty_list" do
    @tag :skip
    test "batch_extract_bytes_sync_empty_list" do
      # batch functions excluded from Elixir binding: unsafe NIF tuple marshalling
      :ok
    end
  end

  describe "batch_extract_bytes_sync_invalid_mime" do
    @tag :skip
    test "batch_extract_bytes_sync_invalid_mime" do
      # batch functions excluded from Elixir binding: unsafe NIF tuple marshalling
      :ok
    end
  end

  describe "batch_file_async_basic" do
    @tag :skip
    test "batch_file_async_basic" do
      # batch functions excluded from Elixir binding: unsafe NIF tuple marshalling
      :ok
    end
  end

  describe "batch_file_async_not_found" do
    @tag :skip
    test "batch_file_async_not_found" do
      # batch functions excluded from Elixir binding: unsafe NIF tuple marshalling
      :ok
    end
  end

  describe "batch_file_not_found" do
    @tag :skip
    test "batch_file_not_found" do
      # batch functions excluded from Elixir binding: unsafe NIF tuple marshalling
      :ok
    end
  end

  describe "batch_file_partial" do
    @tag :skip
    test "batch_file_partial" do
      # batch functions excluded from Elixir binding: unsafe NIF tuple marshalling
      :ok
    end
  end

  describe "batch_file_sync_basic" do
    @tag :skip
    test "batch_file_sync_basic" do
      # batch functions excluded from Elixir binding: unsafe NIF tuple marshalling
      :ok
    end
  end
end
