# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c5b9396b773dc8263bf55403ae885f5a2ddb930140b83455af3c7659da0f7ecd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: document_extractor_management
defmodule E2e.DocumentExtractorManagementTest do
  use ExUnit.Case, async: false

  describe "document_extractors_clear" do
    test "document_extractors_clear" do
      result = Kreuzberg.clear_document_extractors()
    end
  end

  describe "extractors_list" do
    test "extractors_list" do
      result = Kreuzberg.list_document_extractors()
    end
  end
end
