# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c0012448be4e00327689c0c05e2f511411c9fc99a4fc8f44745d064434b738f2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
# E2e tests for category: document_extractor_management
defmodule E2e.DocumentExtractorManagementTest do
  use ExUnit.Case, async: false

  describe "document_extractors_clear" do
    test "document_extractors_clear" do
      result = Kreuzberg.clear_document_extractors()
    end
  end

  describe "extractors_list" do
    test "extractors_list" do
      result = Kreuzberg.list_document_extractors()
    end
  end
end
