# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:111c3ac478d0f48d920ab44bece0257d203cd568bcb7ef2f3927c11b739bb0d3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: embedding_backend_management
defmodule E2e.EmbeddingBackendManagementTest do
  use ExUnit.Case, async: false

  describe "embedding_backends_clear" do
    test "embedding_backends_clear" do
      result = Kreuzberg.clear_embedding_backends()
      assert is_nil(result) or String.trim(result) == ""
    end
  end

  describe "embedding_backends_list" do
    test "embedding_backends_list" do
      result = Kreuzberg.list_embedding_backends()
    end
  end
end
