# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7a2af3f1ee1f82b2d25b0ab58aebf48a036e634c41c91eeb08f2251b75b35b35
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: embed_async_pending
defmodule E2e.EmbedAsyncPendingTest do
  use ExUnit.Case, async: false

  describe "embed_texts_async_empty_input" do
    test "embed_texts_async_empty_input" do
      {:ok, result} = Kreuzberg.embed_texts_async([])
      assert length(result) == 0
    end
  end

  describe "embed_texts_async_happy" do
    test "embed_texts_async_happy" do
      {:ok, result} = Kreuzberg.embed_texts_async(["First", "Second"])
      assert length(result) >= 2
    end
  end

  describe "embed_texts_async_preset_switch" do
    test "embed_texts_async_preset_switch" do
      {:ok, result} = Kreuzberg.embed_texts_async(["Text"], "{\"model\":{\"name\":\"balanced\",\"type\":\"preset\"}}")
    end
  end
end
