# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: ocr_backend_management
defmodule E2e.OcrBackendManagementTest do
  use ExUnit.Case, async: false

  describe "ocr_backends_clear" do
    test "ocr_backends_clear" do
      result = Kreuzberg.clear_ocr_backends()
    end
  end

  describe "ocr_backends_list" do
    test "ocr_backends_list" do
      result = Kreuzberg.list_ocr_backends()
    end
  end

  describe "ocr_backends_unregister" do
    test "ocr_backends_unregister" do
      result = Kreuzberg.unregister_ocr_backend("nonexistent-backend-xyz")
    end
  end
end
