# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7a2af3f1ee1f82b2d25b0ab58aebf48a036e634c41c91eeb08f2251b75b35b35
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: renderer_management
defmodule E2e.RendererManagementTest do
  use ExUnit.Case, async: false

  describe "renderers_clear" do
    test "renderers_clear" do
      result = Kreuzberg.clear_renderers()
    end
  end

  describe "renderers_list" do
    test "renderers_list" do
      result = Kreuzberg.list_renderers()
    end
  end
end
