# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:267e1b8e1c7198b021c6f7c1c7679ec0a2a72122fb59b9aa399c0d37802dff5c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: renderer_management
defmodule E2e.RendererManagementTest do
  use ExUnit.Case, async: false

  describe "renderers_clear" do
    test "renderers_clear" do
      result = Kreuzberg.clear_renderers()
      assert is_nil(result) or String.trim(result) == ""
    end
  end

  describe "renderers_list" do
    test "renderers_list" do
      result = Kreuzberg.list_renderers()
    end
  end
end
