// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:22ac650e2bf03c10477d9d65caaba78e071e265995dd1a6152bf231f73a6e8f9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;
using static Kreuzberg.KreuzbergLib;

namespace Kreuzberg
{
    /// <summary>E2e tests for category: document_extractor_management.</summary>
    public class DocumentExtractorManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_DocumentExtractorsClear()
        {
            // Clear all document extractors and verify list is empty
            var result = KreuzbergLib.ClearDocumentExtractors();
    Assert.True(string.IsNullOrEmpty(result?.ToString()));

        }

        [Fact]
        public void Test_ExtractorsList()
        {
            // List all registered document extractors
            var result = KreuzbergLib.ListDocumentExtractors();

        }


    }
}
