// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bdaf3a01a6a2673c3c60f6b70b84688eaf54e07ebfca9ad15ffb0809adf4c79f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;
using static Kreuzberg.KreuzbergLib;

namespace Kreuzberg
{
    /// <summary>E2e tests for category: ocr_backend_management.</summary>
    public class OcrBackendManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_OcrBackendsClear()
        {
            // Clear all OCR backends and verify list is empty
            var result = KreuzbergLib.ClearOcrBackends();
    Assert.True(string.IsNullOrEmpty(result?.ToString()));

        }

        [Fact]
        public void Test_OcrBackendsList()
        {
            // List all registered OCR backends
            var result = KreuzbergLib.ListOcrBackends();

        }

        [Fact]
        public void Test_OcrBackendsUnregister()
        {
            // Unregister nonexistent OCR backend gracefully
            var result = KreuzbergLib.UnregisterOcrBackend("nonexistent-backend-xyz");

        }


    }
}
