// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dcd53c1ffa1fdf50991f98dc8edf67b04678a71573693591a825a04b7fe95e79
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;
using static Kreuzberg.KreuzbergLib;

namespace Kreuzberg
{
    /// <summary>E2e tests for category: post_processor_management.</summary>
    public class PostProcessorManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_PostProcessorsClear()
        {
            // Clear all post-processors and verify list is empty
            KreuzbergLib.ClearPostProcessors();
        }

        [Fact]
        public void Test_PostProcessorsList()
        {
            // List all registered post-processors
            var result = KreuzbergLib.ListPostProcessors();

        }


    }
}
