// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:228da491b8691b06c0de5f3df81e30ccb1b261fdc47bfbedb6b51c1e90fb4826
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;
using static Kreuzberg.KreuzbergLib;

namespace Kreuzberg
{
    /// <summary>E2e tests for category: renderer_management.</summary>
    public class RendererManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_RenderersClear()
        {
            // Clear all renderers and verify list is empty
            var result = KreuzbergLib.ClearRenderers();
    Assert.True(string.IsNullOrEmpty(result?.ToString()));

        }

        [Fact]
        public void Test_RenderersList()
        {
            // List all registered renderers
            var result = KreuzbergLib.ListRenderers();

        }


    }
}
