# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7a2af3f1ee1f82b2d25b0ab58aebf48a036e634c41c91eeb08f2251b75b35b35
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Exception hierarchy."""


class KreuzbergError(Exception):
    """Main error type for all Kreuzberg operations."""


class IoError(KreuzbergError):
    """Io error."""


class ParsingError(KreuzbergError):
    """Parsing error."""


class OcrError(KreuzbergError):
    """Ocr error."""


class ValidationError(KreuzbergError):
    """Validation error."""


class CacheError(KreuzbergError):
    """Cache error."""


class ImageProcessingError(KreuzbergError):
    """Image processing error."""


class SerializationError(KreuzbergError):
    """Serialization error."""


class MissingDependencyError(KreuzbergError):
    """Missing dependency error."""


class PluginError(KreuzbergError):
    """Plugin error."""


class LockPoisonedError(KreuzbergError):
    """Lock poisoned error."""


class UnsupportedFormatError(KreuzbergError):
    """Unsupported format error."""


class EmbeddingError(KreuzbergError):
    """Embedding error."""


class KreuzbergTimeoutError(KreuzbergError):
    """Kreuzberg timeout error."""


class CancelledError(KreuzbergError):
    """Cancelled error."""


class SecurityError(KreuzbergError):
    """Security error."""


class OtherError(KreuzbergError):
    """Other error."""
