// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a4b2535e507ad7d6891f9f696c62001bdc930272512ef1c9e8e151cb54027e5f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: embed_extra

use kreuzberg::embed_texts;

#[test]
fn test_embed_texts_batch() {
    // Batch embed texts
    let texts_json: serde_json::Value = serde_json::from_str(r#"["Hello","World"]"#).unwrap();
    let texts = serde_json::from_value::<Vec<String>>(texts_json).unwrap();
    let config_json: serde_json::Value =
        serde_json::from_str(r#"{"model":{"name":"balanced","type":"preset"}}"#).unwrap();
    let config = serde_json::from_value(config_json).unwrap();
    let _ = embed_texts(texts, &config).expect("should succeed");
}
