// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: post_processor_management

use kreuzberg::{clear_post_processors, list_post_processors};

#[test]
fn test_post_processors_clear() {
    // Clear all post-processors and verify list is empty
    let _ = clear_post_processors();
}

#[test]
fn test_post_processors_list() {
    // List all registered post-processors
    let _ = list_post_processors();
}
