// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a4b2535e507ad7d6891f9f696c62001bdc930272512ef1c9e8e151cb54027e5f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: registry

use kreuzberg::{
    list_document_extractors, list_embedding_backends, list_ocr_backends, list_post_processors, list_renderers,
    list_validators,
};

#[test]
fn test_list_document_extractors() {
    // List document extractors
    let _ = list_document_extractors();
}

#[test]
fn test_list_embedding_backends() {
    // List embedding backends
    let _ = list_embedding_backends();
}

#[test]
fn test_list_ocr_backends() {
    // List OCR backends
    let _ = list_ocr_backends();
}

#[test]
fn test_list_post_processors() {
    // List post-processors
    let _ = list_post_processors();
}

#[test]
fn test_list_renderers() {
    // List renderers
    let _ = list_renderers();
}

#[test]
fn test_list_validators() {
    // List validators
    let _ = list_validators();
}
