<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7a2af3f1ee1f82b2d25b0ab58aebf48a036e634c41c91eeb08f2251b75b35b35
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\ExtractionConfig;

/** E2e tests for category: document_extractor_management. */
final class DocumentExtractorManagementTest extends TestCase
{

    /** Clear all document extractors and verify list is empty */
    public function test_document_extractors_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::clearDocumentExtractors();


    }


    /** List all registered document extractors */
    public function test_extractors_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listDocumentExtractors(["setup" => ["lazy_init_required" => ["init_action" => "extract_file_sync", "init_data" => ["create_temp_file" => true, "temp_file_content" => "%PDF-1.4\n%EOF\n", "temp_file_name" => "test.pdf"], "languages" => ["go"]]]]);


    }

}
