<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fe4fffc8c25b12cb50fc0081bf02547446147cc300fbd1af05e4cc40dd058bb5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;use Kreuzberg\ExtractionConfig;
/** E2e tests for category: document_extractor_management. */
final class DocumentExtractorManagementTest extends TestCase
{

    /** Clear all document extractors and verify list is empty */
    public function test_document_extractors_clear(): void
    {        $result = Kreuzberg::clear_document_extractors();
            $this->assertEmpty($result->getResult());

    }


    /** List all registered document extractors */
    public function test_extractors_list(): void
    {        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listDocumentExtractors(["setup" => ["lazy_init_required" => ["init_action" => "extract_file_sync", "init_data" => ["create_temp_file" => true, "temp_file_content" => "%PDF-1.4\n%EOF\n", "temp_file_name" => "test.pdf"], "languages" => ["go"]]]]);

    }

}
