<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c0012448be4e00327689c0c05e2f511411c9fc99a4fc8f44745d064434b738f2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;use Kreuzberg\ExtractionConfig;
/** E2e tests for category: document_extractor_management. */
final class DocumentExtractorManagementTest extends TestCase
{

    /** Clear all document extractors and verify list is empty */
    public function test_document_extractors_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::clearDocumentExtractors();


    }


    /** List all registered document extractors */
    public function test_extractors_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listDocumentExtractors(["setup" => ["lazy_init_required" => ["init_action" => "extract_file_sync", "init_data" => ["create_temp_file" => true, "temp_file_content" => "%PDF-1.4\n%EOF\n", "temp_file_name" => "test.pdf"], "languages" => ["go"]]]]);


    }

}
