<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dcd53c1ffa1fdf50991f98dc8edf67b04678a71573693591a825a04b7fe95e79
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;use Kreuzberg\ExtractionConfig;
/** E2e tests for category: embedding_backend_management. */
final class EmbeddingBackendManagementTest extends TestCase
{

    /** Clear all embedding backends and verify list is empty */
    public function test_embedding_backends_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::clearEmbeddingBackends();


    }


    /** List all registered embedding backends */
    public function test_embedding_backends_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listEmbeddingBackends();


    }

}
