<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c0012448be4e00327689c0c05e2f511411c9fc99a4fc8f44745d064434b738f2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;use Kreuzberg\ExtractionConfig;
/** E2e tests for category: registry_operations. */
final class RegistryOperationsTest extends TestCase
{

    /** Get file extensions for DOCX MIME type */
    public function test_extensions_docx(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::getExtensionsForMime("application/vnd.openxmlformats-officedocument.wordprocessingml.document");


    }


    /** Get file extensions for HTML MIME type */
    public function test_extensions_html(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::getExtensionsForMime("text/html");


    }


    /** Get file extensions for PDF MIME type */
    public function test_extensions_pdf(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::getExtensionsForMime("application/pdf");


    }

}
