<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:08e96ccdf8aa78cf6b0b86d1272d4a4e0655b6507861695eedee4cb1fdf651dd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;use Kreuzberg\ExtractionConfig;
/** E2e tests for category: renderer_management. */
final class RendererManagementTest extends TestCase
{

    /** Clear all renderers and verify list is empty */
    public function test_renderers_clear(): void
    {        $result = Kreuzberg::clear_renderers();
            $this->assertEmpty($result->getResult());

    }


    /** List all registered renderers */
    public function test_renderers_list(): void
    {        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listRenderers();

    }

}
