<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:78cb967b0be648c497914db9acfa7a09e8ba4cf1e748cb0fd3dcbf79fc4b04a1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;use Kreuzberg\ExtractionConfig;
/** E2e tests for category: validator_management. */
final class ValidatorManagementTest extends TestCase
{

    /** Clear all validators and verify list is empty */
    public function test_validators_clear(): void
    {        $result = Kreuzberg::clear_validators();
            $this->assertEmpty($result->getResult());

    }


    /** List all registered validators */
    public function test_validators_list(): void
    {        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listValidators();

    }

}
