<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\ExtractionConfig;

/** E2e tests for category: validator_management. */
final class ValidatorManagementTest extends TestCase
{

    /** Clear all validators and verify list is empty */
    public function test_validators_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::clearValidators();


    }


    /** List all registered validators */
    public function test_validators_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listValidators();


    }

}
