// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:annotation",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
)

package dev.kreuzberg

/**
 * A single file extracted from an archive.
 *
 * When archives (ZIP, TAR, 7Z, GZIP) are extracted with recursive extraction
 * enabled, each processable file produces its own full `ExtractionResult`.
 */
data class ArchiveEntry(
    /**
     * Archive-relative file path (e.g. "folder/document.pdf").
     */
    val path: String,
    /**
     * Detected MIME type of the file.
     */
    val mimeType: String,
    /**
     * Full extraction result for this file.
     */
    val result: ExtractionResult,
)
