// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:annotation",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
)

package dev.kreuzberg

/**
 * MIME type detection response.
 */
data class DetectResponse(
    /**
     * Detected MIME type
     */
    val mimeType: String,
    /**
     * Original filename (if provided)
     */
    val filename: String?,
)
