// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:annotation",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
)

package dev.kreuzberg

/**
 * Excel/spreadsheet format metadata.
 *
 * Identifies the document as a spreadsheet source via the `FormatMetadata.Excel`
 * discriminant. Sheet count and sheet names are stored inside this struct.
 */
data class ExcelMetadata(
    /**
     * Number of sheets in the workbook.
     */
    val sheetCount: Int?,
    /**
     * Names of all sheets in the workbook.
     */
    val sheetNames: List<String>?,
)
