// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:annotation",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
)

package dev.kreuzberg

/**
 * ONNX Runtime execution provider type.
 *
 * Determines which hardware backend is used for model inference.
 * `Auto` (default) selects the best available provider per platform.
 */
enum class ExecutionProviderType {
    /**
     * Auto-select: CoreML on macOS, CUDA on Linux, CPU elsewhere.
     */
    AUTO,
    /**
     * CPU execution provider (always available).
     */
    CPU,
    /**
     * Apple CoreML (macOS/iOS Neural Engine + GPU).
     */
    CORE_ML,
    /**
     * NVIDIA CUDA GPU acceleration.
     */
    CUDA,
    /**
     * NVIDIA TensorRT (optimized CUDA inference).
     */
    TENSOR_RT,
}
