// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
)

package dev.kreuzberg

/** The complete diff between two `ExtractionResult` values. */
data class ExtractionDiff(
    /**
     * Unified-diff hunks for the `content` field.
     *
     * Empty when the content is identical.
     */
    val contentDiff: List<DiffHunk> = emptyList(),
    /** Tables present in `b` but not in `a` (by index position, excess right-side tables). */
    val tablesAdded: List<Table> = emptyList(),
    /** Tables present in `a` but not in `b` (by index position, excess left-side tables). */
    val tablesRemoved: List<Table> = emptyList(),
    /** Cell-level changes for table pairs that share the same index and dimensions. */
    val tablesChanged: List<TableDiff> = emptyList(),
    /**
     * Metadata changes in a simplified add/remove/change map.
     *
     * Shape: `{ "added": {key: value, ...}, "removed": {key: value, ...},
     *           "changed": {key: {from: v1, to: v2}, ...} }`.
     *
     * Approximates RFC 6902 JSON Patch semantics without pulling in an extra crate.
     */
    val metadataChanged: Any,
    /** Changes to embedded archive children. */
    val embeddedChanges: EmbeddedChanges,
)
