// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:annotation",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
)

package dev.kreuzberg

/**
 * Image type classification.
 */
enum class ImageType {
    /**
     * Data URI image
     */
    DATA_URI,
    /**
     * Inline SVG
     */
    INLINE_SVG,
    /**
     * External image URL
     */
    EXTERNAL,
    /**
     * Relative path image
     */
    RELATIVE,
}
