// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:annotation",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
)

package dev.kreuzberg

/**
 * Inline element within a block.
 *
 * Represents text with formatting, links, images, etc.
 */
data class InlineElement(
    /**
     * Type of inline element
     */
    val elementType: InlineType,
    /**
     * Text content
     */
    val content: String,
    /**
     * Element attributes
     */
    val attributes: String?,
    /**
     * Additional metadata (e.g., href for links, src/alt for images)
     */
    val metadata: Map<String, String>?,
)
