// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:annotation",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
)

package dev.kreuzberg

/**
 * Link element metadata.
 */
data class LinkMetadata(
    /**
     * The href URL value
     */
    val href: String,
    /**
     * Link text content (normalized)
     */
    val text: String,
    /**
     * Optional title attribute
     */
    val title: String?,
    /**
     * Link type classification
     */
    val linkType: LinkType,
    /**
     * Rel attribute values
     */
    val rel: List<String>,
    /**
     * Additional attributes as key-value pairs
     */
    val attributes: List<String>,
)
