// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:annotation",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
)

package dev.kreuzberg

/**
 * OCR backend types.
 */
enum class OcrBackendType {
    /**
     * Tesseract OCR (native Rust binding)
     */
    TESSERACT,
    /**
     * EasyOCR (Python-based, via FFI)
     */
    EASY_O_C_R,
    /**
     * PaddleOCR (Python-based, via FFI)
     */
    PADDLE_O_C_R,
    /**
     * Custom/third-party OCR backend
     */
    CUSTOM,
}
