// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:annotation",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
)

package dev.kreuzberg

/**
 * Rotation information for an OCR element.
 */
data class OcrRotation(
    /**
     * Rotation angle in degrees (0, 90, 180, 270 for PaddleOCR).
     */
    val angleDegrees: Double,
    /**
     * Confidence score for the rotation detection.
     */
    val confidence: Double?,
)
