// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:annotation",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
)

package dev.kreuzberg

/**
 * Type of paginated unit in a document.
 *
 * Distinguishes between different types of "pages" (PDF pages, presentation slides, spreadsheet sheets).
 */
enum class PageUnitType {
    /**
     * Standard document pages (PDF, DOCX, images)
     */
    PAGE,
    /**
     * Presentation slides (PPTX, ODP)
     */
    SLIDE,
    /**
     * Spreadsheet sheets (XLSX, ODS)
     */
    SHEET,
}
