// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:annotation",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
)

package dev.kreuzberg

/**
 * Page extraction and tracking configuration.
 *
 * Controls how pages are extracted, tracked, and represented in the extraction results.
 * When `null`, page tracking is disabled.
 *
 * Page range tracking in chunk metadata (first_page/last_page) is automatically enabled
 * when page boundaries are available and chunking is configured.
 */
data class PageConfig(
    /**
     * Extract pages as separate array (ExtractionResult.pages)
     */
    val extractPages: Boolean,
    /**
     * Insert page markers in main content string
     */
    val insertPageMarkers: Boolean,
    /**
     * Page marker format (use {page_num} placeholder)
     * Default: "\n\n<!-- PAGE {page_num} -->\n\n"
     */
    val markerFormat: String,
)
