// Generated by alef. Do not edit by hand.
// alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
)

package dev.kreuzberg

/** Configuration for the page-classification post-processor. */
data class PageClassificationConfig(
    /**
     * Minijinja prompt template. Receives `{{ labels }}` (joined list), `{{ page_text }}`
     * and `{{ multi_label }}` variables. `null` lets the backend pick a sensible default.
     */
    val promptTemplate: String? = null,
    /** The set of labels the classifier may emit. Must contain at least one entry. */
    val labels: List<String> = emptyList(),
    /** Allow multiple labels per page. Single-label mode returns at most one label. */
    val multiLabel: Boolean,
    /** LLM configuration used for classification. */
    val llm: LlmConfig,
)
