// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:annotation",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
)

package dev.kreuzberg

/**
 * Type of PDF annotation.
 */
enum class PdfAnnotationType {
    /**
     * Sticky note / text annotation
     */
    TEXT,
    /**
     * Highlighted text region
     */
    HIGHLIGHT,
    /**
     * Hyperlink annotation
     */
    LINK,
    /**
     * Rubber stamp annotation
     */
    STAMP,
    /**
     * Underline text markup
     */
    UNDERLINE,
    /**
     * Strikeout text markup
     */
    STRIKE_OUT,
    /**
     * Any other annotation type
     */
    OTHER,
}
