// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:annotation",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
)

package dev.kreuzberg

/**
 * A non-fatal warning from a processing pipeline stage.
 *
 * Captures errors from optional features that don't prevent extraction
 * but may indicate degraded results.
 */
data class ProcessingWarning(
    /**
     * The pipeline stage or feature that produced this warning
     * (e.g., "embedding", "chunking", "language_detection", "output_format").
     */
    val source: String,
    /**
     * Human-readable description of what went wrong.
     */
    val message: String,
)
