// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:annotation",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
)

package dev.kreuzberg

/**
 * RAKE-specific parameters.
 */
data class RakeParams(
    /**
     * Minimum word length to consider (default: 1).
     */
    val minWordLength: Long,
    /**
     * Maximum words in a keyword phrase (default: 3).
     */
    val maxWordsPerPhrase: Long,
)
