// Generated by alef. Do not edit by hand.
// alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
)

package dev.kreuzberg

/**
 * One user-supplied literal term to redact.
 *
 * Matched as a regex-escaped substring (so callers do not need to escape
 * metacharacters themselves). Case-insensitive by default — set
 * `Self.case_sensitive` to `true` for exact byte-match semantics.
 */
data class RedactionTerm(
    /** Custom category label surfaced in `RedactionFinding.category`. */
    val label: String,
    /** Literal value to match. Regex metacharacters are escaped automatically. */
    val value: String,
    /** When `true`, match the value as-is; otherwise match ASCII-case-insensitively. */
    val caseSensitive: Boolean,
)
