// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:annotation",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
)

package dev.kreuzberg

/**
 * Structured table grid with cell-level metadata.
 *
 * Stores row/column dimensions and a flat list of cells with position info.
 */
data class TableGrid(
    /**
     * Number of rows in the table.
     */
    val rows: Int,
    /**
     * Number of columns in the table.
     */
    val cols: Int,
    /**
     * All cells in row-major order.
     */
    val cells: List<GridCell>,
)
