// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e5d524d53baadb5b39391678c0414c96673dd1da1fadce290dd59aeac847a3db
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import XCTest
import Foundation
import Kreuzberg
import RustBridge

/// E2e tests for category: ocr_backend_management.
final class OcrBackendManagementTests: XCTestCase {
    func testOcrBackendsClear() throws {
        // Clear all OCR backends and verify list is empty
        let result = try clearOcrBackends()
        XCTAssertEqual(result.count, 0, "expected empty value")
    }

    func testOcrBackendsList() throws {
        // List all registered OCR backends
        let result = try listOcrBackends()
    }

    func testOcrBackendsUnregister() throws {
        // Unregister nonexistent OCR backend gracefully
        let result = try unregisterOcrBackend("nonexistent-backend-xyz")
    }

}
