// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c0012448be4e00327689c0c05e2f511411c9fc99a4fc8f44745d064434b738f2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Kreuzberg
import RustBridge

/// E2e tests for category: post_processor_management.
final class PostProcessorManagementTests: XCTestCase {
    func testPostProcessorsClear() throws {
        // Clear all post-processors and verify list is empty
        let result = try Kreuzberg.clearPostProcessors()
    }

    func testPostProcessorsList() throws {
        // List all registered post-processors
        let result = try Kreuzberg.listPostProcessors()
    }

}
