// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:eaa521348bba10463fec200f9d7408360edc6452875999f7a7f158c04db3d0bd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import XCTest
import Foundation
import Kreuzberg
import RustBridge

/// E2e tests for category: registry.
final class RegistryTests: XCTestCase {
    func testListDocumentExtractors() throws {
        // List document extractors
        let result = try listDocumentExtractors()
    }

    func testListEmbeddingBackends() throws {
        // List embedding backends
        let result = try listEmbeddingBackends()
    }

    func testListOcrBackends() throws {
        // List OCR backends
        let result = try listOcrBackends()
    }

    func testListPostProcessors() throws {
        // List post-processors
        let result = try listPostProcessors()
    }

    func testListRenderers() throws {
        // List renderers
        let result = try listRenderers()
    }

    func testListValidators() throws {
        // List validators
        let result = try listValidators()
    }

}
