// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Kreuzberg
import RustBridge

/// E2e tests for category: renderer_management.
final class RendererManagementTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _existing = ProcessInfo.processInfo.environment["SUT_URL"]
    }

    func testRenderersClear() throws {
        // Clear all renderers and verify list is empty
        let result = try Kreuzberg.clearRenderers()
    }

    func testRenderersList() throws {
        // List all registered renderers
        let result = try Kreuzberg.listRenderers()
    }

}
