// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a4b2535e507ad7d6891f9f696c62001bdc930272512ef1c9e8e151cb54027e5f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Kreuzberg
import RustBridge

/// E2e tests for category: validator_management.
final class ValidatorManagementTests: XCTestCase {
    func testValidatorsClear() throws {
        // Clear all validators and verify list is empty
        let result = try Kreuzberg.clearValidators()
    }

    func testValidatorsList() throws {
        // List all registered validators
        let result = try Kreuzberg.listValidators()
    }

}
