// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a4b2535e507ad7d6891f9f696c62001bdc930272512ef1c9e8e151cb54027e5f
#nullable enable

using System;

namespace Kreuzberg;

public class CacheException : KreuzbergErrorException
{
    public CacheException(string message) : base(message) { }

    public CacheException(string message, Exception innerException) : base(message, innerException) { }
}
