// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1fe313c58285449a304fd6e6cc737296bc9e4e8d13c963692ff17e26b9e4bc3c
#nullable enable

using System;

namespace Kreuzberg;

public class CancelledException : KreuzbergErrorException
{
    public CancelledException(string message) : base(message) { }

    public CancelledException(string message, Exception innerException) : base(message, innerException) { }
}
