// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3c9134676a4f2588f3d09456ae57c8cced951a8a705a90eacd29e9cc012a8ecd
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Content rendering mode for code extraction.
///
/// Controls how extracted code content is represented in the `content` field
/// of `ExtractionResult`.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum CodeContentMode
{    /// <summary>
     /// Use TSLP semantic chunks as content (default).
     /// </summary>
    [JsonPropertyName("chunks")]
    Chunks,    /// <summary>
               /// Use raw source code as content.
               /// </summary>
    [JsonPropertyName("raw")]
    Raw,    /// <summary>
            /// Emit function/class headings + docstrings (no code bodies).
            /// </summary>
    [JsonPropertyName("structure")]
    Structure,
}
