// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e5418130e5748acd755161fcc95cfaf7c557e63d9bb48553e37979bea6dee803
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Page-level detection result containing all detections and page metadata.
/// </summary>
public sealed record DetectionResult
{
    [JsonPropertyName("page_width")]
    public uint PageWidth { get; init; } = 0;

    [JsonPropertyName("page_height")]
    public uint PageHeight { get; init; } = 0;

    [JsonPropertyName("detections")]
    public List<LayoutDetection> Detections { get; init; } = [];


    /// <summary>
    /// Parse a <see cref="DetectionResult"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static DetectionResult FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<DetectionResult>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse DetectionResult from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse DetectionResult from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
