// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5bc1e9005910134826fc44171dd65e01912d8e6e81415cd49e9dd77553b19758
#nullable enable

using System;

namespace Kreuzberg;

public class EmbeddingException : KreuzbergErrorException
{
    public EmbeddingException(string message) : base(message) { }

    public EmbeddingException(string message, Exception innerException) : base(message, innerException) { }
}
