// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f4915668c82d41c304b09fa796d61d202f3c93a870854795b77c16270ffd0b7d
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// ONNX Runtime execution provider type.
///
/// Determines which hardware backend is used for model inference.
/// `Auto` (default) selects the best available provider per platform.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ExecutionProviderType
{    /// <summary>
     /// Auto-select: CoreML on macOS, CUDA on Linux, CPU elsewhere.
     /// </summary>
    [JsonPropertyName("auto")]
    Auto,    /// <summary>
             /// CPU execution provider (always available).
             /// </summary>
    [JsonPropertyName("cpu")]
    Cpu,    /// <summary>
            /// Apple CoreML (macOS/iOS Neural Engine + GPU).
            /// </summary>
    [JsonPropertyName("coreml")]
    CoreMl,    /// <summary>
               /// NVIDIA CUDA GPU acceleration.
               /// </summary>
    [JsonPropertyName("cuda")]
    Cuda,    /// <summary>
             /// NVIDIA TensorRT (optimized CUDA inference).
             /// </summary>
    [JsonPropertyName("tensorrt")]
    TensorRt,
}
