// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:bf2a2d2f6175e4985d20965dfaf9ba45d83d298209e4279b30d9533273925131
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// How the extracted text was produced.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ExtractionMethod
{
    [JsonPropertyName("native")]
    Native, [JsonPropertyName("ocr")]
    Ocr, [JsonPropertyName("mixed")]
    Mixed,
}
