// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:dd7f972e4100ae227bd08b6837a16aa216d8eaee87b852962abb9939a26432de
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum FracType
{
    [JsonPropertyName("bar")]
    Bar, [JsonPropertyName("nobar")]
    NoBar, [JsonPropertyName("linear")]
    Linear, [JsonPropertyName("skewed")]
    Skewed,
}
