// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1bc6bee3d8309b7dd48a8267475e8f309f87e4e7d4d4b4c59b2d169a8b6958f4
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Built-in HTML theme selection.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum HtmlTheme
{    /// <summary>
     /// Sensible defaults: system font stack, neutral colours, readable line
     /// measure. CSS custom properties (`--kb-*`) are all defined so user CSS
     /// can override individual values.
     /// </summary>
    [JsonPropertyName("default")]
    Default,    /// <summary>
                /// GitHub Markdown-inspired palette and spacing.
                /// </summary>
    [JsonPropertyName("github")]
    GitHub,    /// <summary>
               /// Dark background, light text.
               /// </summary>
    [JsonPropertyName("dark")]
    Dark,    /// <summary>
             /// Minimal light theme with generous whitespace.
             /// </summary>
    [JsonPropertyName("light")]
    Light,    /// <summary>
              /// No built-in stylesheet emitted. CSS custom properties are still defined
              /// on `:root` so user stylesheets can reference `var(--kb-*)` tokens.
              /// </summary>
    [JsonPropertyName("unstyled")]
    Unstyled,
}
