// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9eb6db6e405d991b36c45be45b00af41548aca1a03261cb87e0e0615ff46ab56
#nullable enable

using System;

namespace Kreuzberg;

public class IoException : KreuzbergErrorException
{
    public IoException(string message) : base(message) { }

    public IoException(string message, Exception innerException) : base(message, innerException) { }
}
