// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
#nullable enable

using System;

namespace Kreuzberg;

public class KreuzbergException : Exception
{
    public int Code { get; }

    public KreuzbergException(int code, string message) : base(message)
    {
        Code = code;
    }

    public KreuzbergException(string message) : base(message)
    {
        Code = 0;
    }

    public KreuzbergException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
