// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:cc48aa11c21b9a085c66a8986b3207664edf717ab69f451c3fc51f55e5d4aa59
#nullable enable

using System;

namespace Kreuzberg;

public class MissingDependencyException : KreuzbergErrorException
{
    public MissingDependencyException(string message) : base(message) { }

    public MissingDependencyException(string message, Exception innerException) : base(message, innerException) { }
}
