// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:08a1476531dc623deffa739a57abeac9339d8d82e4acc1f709dde1616a5d62d1
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// OCR backend types.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum OcrBackendType
{    /// <summary>
     /// Tesseract OCR (native Rust binding)
     /// </summary>
    [JsonPropertyName("tesseract")]
    Tesseract,    /// <summary>
                  /// EasyOCR (Python-based, via FFI)
                  /// </summary>
    [JsonPropertyName("easyocr")]
    EasyOcr,    /// <summary>
                /// PaddleOCR (Python-based, via FFI)
                /// </summary>
    [JsonPropertyName("paddleocr")]
    PaddleOcr,    /// <summary>
                  /// Custom/third-party OCR backend
                  /// </summary>
    [JsonPropertyName("custom")]
    Custom,
}
