// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:34897a50f997171f07bae69a258ba9cd4f52f978a51992a579e2484dfc456247
#nullable enable

using System;

namespace Kreuzberg;

public class ParsingException : KreuzbergErrorException
{
    public ParsingException(string message) : base(message) { }

    public ParsingException(string message, Exception innerException) : base(message, innerException) { }
}
