// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a8f9fcf717b379a298794300a143c9e822162ee7fd30e37ecb58d8673d5afec2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Outlook PST archive metadata.
/// </summary>
public sealed record PstMetadata
{
    [JsonPropertyName("message_count")]
    public ulong MessageCount { get; init; } = 0;


    /// <summary>
    /// Parse a <see cref="PstMetadata"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static PstMetadata FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<PstMetadata>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse PstMetadata from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse PstMetadata from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
