// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ba42bfe49aa3dbd4664c195070be22efe4b3c03042f1b7608844609b28dbd661
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ReductionLevel
{
    [JsonPropertyName("off")]
    Off, [JsonPropertyName("light")]
    Light, [JsonPropertyName("moderate")]
    Moderate, [JsonPropertyName("aggressive")]
    Aggressive, [JsonPropertyName("maximum")]
    Maximum,
}
