// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2dba42b39e19c09642310580e057c76f13862903c4300b42f8e56cb58ba8b212
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Result-shape selection for extraction results.
///
/// Distinct from `OutputFormat` (which controls rendering — Plain, Markdown,
/// HTML, etc.). `ResultFormat` controls the *shape* of the result: a unified content
/// blob vs. an element-based decomposition.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ResultFormat
{    /// <summary>
     /// Unified format with all content in `content` field
     /// </summary>
    [JsonPropertyName("unified")]
    Unified,    /// <summary>
                /// Element-based format with semantic element extraction
                /// </summary>
    [JsonPropertyName("element_based")]
    ElementBased,
}
