// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0f932162fcb5ae5699a66e7ecc518de5a68d6fed8d2eb7c2c0f89da3ffd48700
#nullable enable

using System;

namespace Kreuzberg;

public class SecurityException : KreuzbergErrorException
{
    public SecurityException(string message) : base(message) { }

    public SecurityException(string message, Exception innerException) : base(message, innerException) { }
}
