// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ba1618bea14479358deec4a356f0643c580b39081fac1e03646957c9f0c41fa2
#nullable enable

using System;

namespace Kreuzberg;

public class SerializationException : KreuzbergErrorException
{
    public SerializationException(string message) : base(message) { }

    public SerializationException(string message, Exception innerException) : base(message, innerException) { }
}
