# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dcd53c1ffa1fdf50991f98dc8edf67b04678a71573693591a825a04b7fe95e79
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
# E2e tests for category: code

test_that("code_shebang_detection: Test language detection from shebang line via bytes input", {
  result <- jsonlite::fromJSON(extract_file_sync(path = .resolve_fixture("code/script.sh"), mime_type = "text/x-source-code", config = ExtractionConfig$default()), simplifyVector = FALSE)
  expect_equal(trimws(result$mime_type), "text/x-source-code")
  expect_true(nchar(result$content) >= 10)
  expect_true(any(grepl("build", result$content, fixed = TRUE)))
  expect_true(any(grepl("clean", result$content, fixed = TRUE)))
})
