# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:aaa3a6170a1f8ecb7a7189a165ac29f55b85d3fb55dc759ac27e39557882dded
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: embedding_backend_management

test_that("embedding_backends_clear: Clear all embedding backends and verify list is empty", {
  result <- ()
  expect_true(is.null(result) || length(result) == 0 || (length(result) == 1 && (is.na(result) || identical(result, ""))))
})

test_that("embedding_backends_list: List all registered embedding backends", {
  result <- list_embedding_backends()
  expect_true(TRUE)
})
