# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:48c436b93edd7facdc589fb9856467268d55f8e4acc639a2e3ff5672b5b8de4d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: document_extractor_management

test_that("document_extractors_clear: Clear all document extractors and verify list is empty", {
  result <- ()
  expect_true(is.null(result) || length(result) == 0 || (length(result) == 1 && (is.na(result) || identical(result, ""))))
})

test_that("extractors_list: List all registered document extractors", {
  result <- list_document_extractors(list("setup" = list("lazy_init_required" = list("init_action" = "extract_file_sync", "init_data" = list("create_temp_file" = TRUE, "temp_file_content" = "%PDF-1.4\n%EOF\n", "temp_file_name" = "test.pdf"), "languages" = c("go")))))
  expect_true(TRUE)
})
