# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:caebc3d131b03cb582c1cfce436a09b785978f3583c9aa2c5949daafccaf63ae
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: embed_extra

test_that("embed_texts_batch: Batch embed texts", {
  result <- embed_texts_async(texts = c("Hello", "World"), config = EmbeddingConfig$from_json(jsonlite::toJSON(list("model" = list("name" = "balanced", "type" = "preset")), auto_unbox = TRUE)))
  expect_true(TRUE)
})
