# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a4b2535e507ad7d6891f9f696c62001bdc930272512ef1c9e8e151cb54027e5f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: post_processor_management

test_that("post_processors_clear: Clear all post-processors and verify list is empty", {
  invisible(clear_post_processors())
  expect_true(TRUE)
})

test_that("post_processors_list: List all registered post-processors", {
  result <- list_post_processors()
  expect_true(TRUE)
})
