# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7a2af3f1ee1f82b2d25b0ab58aebf48a036e634c41c91eeb08f2251b75b35b35
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: code

test_that("code_shebang_detection: Test language detection from shebang line via bytes input", {
  result <- jsonlite::fromJSON(extract_file_sync(path = .resolve_fixture("code/script.sh"), mime_type = "text/x-source-code", config = ExtractionConfig$default()), simplifyVector = FALSE)
  expect_equal(trimws(result$mime_type), "text/x-source-code")
  expect_true(nchar(result$content) >= 10)
  expect_true(any(grepl("build", result$content, fixed = TRUE)))
  expect_true(any(grepl("clean", result$content, fixed = TRUE)))
})
