# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c0012448be4e00327689c0c05e2f511411c9fc99a4fc8f44745d064434b738f2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
# E2e tests for category: registry

test_that("list_document_extractors: List document extractors", {
  result <- list_document_extractors()
  expect_true(TRUE)
})

test_that("list_embedding_backends: List embedding backends", {
  result <- list_embedding_backends()
  expect_true(TRUE)
})

test_that("list_ocr_backends: List OCR backends", {
  result <- list_ocr_backends()
  expect_true(TRUE)
})

test_that("list_post_processors: List post-processors", {
  result <- list_post_processors()
  expect_true(TRUE)
})

test_that("list_renderers: List renderers", {
  result <- list_renderers()
  expect_true(TRUE)
})

test_that("list_validators: List validators", {
  result <- list_validators()
  expect_true(TRUE)
})
