// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d929f20401c5663a7e6cf59f526ccdc1de0aa072ab41ccc157e7a00a5114bc5b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// E2e tests for category: mime_utilities

test "mime_detect_bytes" {
    // Detect MIME type from file bytes
    const content_bytes = try std.Io.Dir.cwd().readFileAlloc(std.testing.io, "pdf/fake_memo.pdf", std.heap.c_allocator, .unlimited);
    defer std.heap.c_allocator.free(content_bytes);
    _ = try kreuzberg.detect_mime_type_from_bytes(content_bytes);
}

test "mime_detect_image" {
    // Detect MIME type from PNG image bytes
    const content_bytes = try std.Io.Dir.cwd().readFileAlloc(std.testing.io, "images/test_hello_world.png", std.heap.c_allocator, .unlimited);
    defer std.heap.c_allocator.free(content_bytes);
    _ = try kreuzberg.detect_mime_type_from_bytes(content_bytes);
}

test "mime_get_extensions" {
    // Get file extensions for a MIME type
    _ = try kreuzberg.get_extensions_for_mime("application/pdf");
}
