// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4535058b7c60dd87e4e822f79731c8aa528169b151bfd6152fbe84cb1e0eae29
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// E2e tests for category: ocr_backend_management

test "ocr_backends_clear" {
    // Clear all OCR backends and verify list is empty
    const result = try kreuzberg.clear_ocr_backends();
    try testing.expect(result.result.len == 0);
}

test "ocr_backends_list" {
    // List all registered OCR backends
    _ = try kreuzberg.list_ocr_backends();
}

test "ocr_backends_unregister" {
    // Unregister nonexistent OCR backend gracefully
    _ = try kreuzberg.unregister_ocr_backend("nonexistent-backend-xyz");
}
