// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:da858c43551264660419f2c20d9642a068c43e9f84a576b874a9063e1775785f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// E2e tests for category: renderer_management

test "renderers_clear" {
    // Clear all renderers and verify list is empty
    const result = try kreuzberg.clear_renderers();
    try testing.expect(result.result.len == 0);
}

test "renderers_list" {
    // List all registered renderers
    _ = try kreuzberg.list_renderers();
}
