<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c5b9396b773dc8263bf55403ae885f5a2ddb930140b83455af3c7659da0f7ecd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Kreuzberg;

/**
 * liter-llm-backed NER backend.
 */
final class LlmBackend
{
    /**
     * @param array<EntityCategory> $categories
     * @return array<Entity>
     */
    public function detect(string $text, array $categories): array
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    /**
     * @param array<EntityCategory> $categories
     * @param array<string> $custom_labels
     * @return array<Entity>
     */
    public function detectWithCustom(string $text, array $categories, array $custom_labels): array
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    public static function new(LlmConfig $config): LlmBackend
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
