// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dcd53c1ffa1fdf50991f98dc8edf67b04678a71573693591a825a04b7fe95e79
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;
import dev.kreuzberg.JsonUtil;

/** E2e tests for category: code. */
class CodeTest {

    @Test
    void testCodeShebangDetection() throws Exception {
        // Test language detection from shebang line via bytes input
        var result = Kreuzberg.extractFileSync(java.nio.file.Path.of("code/script.sh"), "text/x-source-code", ExtractionConfig.builder().build());
assertEquals("text/x-source-code", result.mimeType().trim());assertTrue(result.content().length() >= 10, "expected length >= 10");assertTrue(result.content().contains("build"), "expected to contain: " + "build");assertTrue(result.content().contains("clean"), "expected to contain: " + "clean");
    }

}
