// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;
import dev.kreuzberg.JsonUtil;

/** E2e tests for category: document_extractor_management. */
public class DocumentExtractorManagementTest {

    @Test
    void testDocumentExtractorsClear() throws Exception {
        // Clear all document extractors and verify list is empty
        Kreuzberg.clearDocumentExtractors();


    }


    @Test
    void testExtractorsList() throws Exception {
        // List all registered document extractors
        var result = Kreuzberg.listDocumentExtractors();


    }

}
