// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7a2af3f1ee1f82b2d25b0ab58aebf48a036e634c41c91eeb08f2251b75b35b35
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;
import dev.kreuzberg.JsonUtil;

/** E2e tests for category: ocr_backend_management. */
public class OcrBackendManagementTest {

    @Test
    void testOcrBackendsClear() throws Exception {
        // Clear all OCR backends and verify list is empty
        Kreuzberg.clearOcrBackends();


    }


    @Test
    void testOcrBackendsList() throws Exception {
        // List all registered OCR backends
        var result = Kreuzberg.listOcrBackends();


    }


    @Test
    void testOcrBackendsUnregister() throws Exception {
        // Unregister nonexistent OCR backend gracefully
        Kreuzberg.unregisterOcrBackend("nonexistent-backend-xyz");


    }

}
