// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7a2af3f1ee1f82b2d25b0ab58aebf48a036e634c41c91eeb08f2251b75b35b35
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;
import dev.kreuzberg.JsonUtil;

/** E2e tests for category: renderer_management. */
public class RendererManagementTest {

    @Test
    void testRenderersClear() throws Exception {
        // Clear all renderers and verify list is empty
        Kreuzberg.clearRenderers();


    }


    @Test
    void testRenderersList() throws Exception {
        // List all registered renderers
        var result = Kreuzberg.listRenderers();


    }

}
