// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c0012448be4e00327689c0c05e2f511411c9fc99a4fc8f44745d064434b738f2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;
import dev.kreuzberg.JsonUtil;

/** E2e tests for category: renderer_management. */
class RendererManagementTest {

    @Test
    void testRenderersClear() throws Exception {
        // Clear all renderers and verify list is empty
        Kreuzberg.clearRenderers();

    }


    @Test
    void testRenderersList() throws Exception {
        // List all registered renderers
        var result = Kreuzberg.listRenderers();

    }

}
