// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c0012448be4e00327689c0c05e2f511411c9fc99a4fc8f44745d064434b738f2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * dBASE (DBF) file metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DbfMetadata.Builder.class)
public record DbfMetadata(
    @JsonProperty("record_count") long recordCount,
    @JsonProperty("field_count") long fieldCount,
    @Nullable @JsonProperty("fields") List<DbfFieldInfo> fields
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @JsonProperty("record_count")
private long recordCount = 0;
        @JsonProperty("field_count")
private long fieldCount = 0;
private List<DbfFieldInfo> fields = null;

        /** Sets the recordCount field. */
        @JsonProperty("record_count")
        public Builder withRecordCount(final long value) {
            this.recordCount = value;
            return this;
        }

        /** Sets the fieldCount field. */
        @JsonProperty("field_count")
        public Builder withFieldCount(final long value) {
            this.fieldCount = value;
            return this;
        }

        /** Sets the fields field. */
        @JsonProperty("fields")
        public Builder withFields(final @Nullable List<DbfFieldInfo> value) {
            this.fields = value;
            return this;
        }

        /** Builds the DbfMetadata instance. */
        public DbfMetadata build() {
            return new DbfMetadata(
                recordCount,
                fieldCount,
                fields
            );
        }
    }
    // CPD-ON
}
