// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7a2af3f1ee1f82b2d25b0ab58aebf48a036e634c41c91eeb08f2251b75b35b35
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Image element in Djot.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DjotImage.Builder.class)
public record DjotImage(
    /**
     * Image source URL or path
     */
    @JsonProperty("src") String src,
    /**
     * Alternative text
     */
    @JsonProperty("alt") String alt,
    /**
     * Optional title
     */
    @Nullable @JsonProperty("title") String title
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

private String src = "";
private String alt = "";
private String title = null;

        /** Sets the src field. */
        @JsonProperty("src")
        public Builder withSrc(final String value) {
            this.src = value;
            return this;
        }

        /** Sets the alt field. */
        @JsonProperty("alt")
        public Builder withAlt(final String value) {
            this.alt = value;
            return this;
        }

        /** Sets the title field. */
        @JsonProperty("title")
        public Builder withTitle(final @Nullable String value) {
            this.title = value;
            return this;
        }

        /** Builds the DjotImage instance. */
        public DjotImage build() {
            return new DjotImage(
                src,
                alt,
                title
            );
        }
    }
    // CPD-ON
}
