// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Configuration for email extraction.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EmailConfig.Builder.class)
@SuppressWarnings("PMD")
public record EmailConfig(@Nullable @JsonProperty("msg_fallback_codepage") Integer msgFallbackCodepage) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @JsonProperty("msg_fallback_codepage")
private Integer msgFallbackCodepage = null;

        /** Sets the msgFallbackCodepage field. */
        @JsonProperty("msg_fallback_codepage")
        public Builder withMsgFallbackCodepage(final @Nullable int value) {
            this.msgFallbackCodepage = value;
            return this;
        }

        /** Builds the EmailConfig instance. */
        public EmailConfig build() {
            return new EmailConfig(
                msgFallbackCodepage
            );
        }
    }
    // CPD-ON
}
