// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7a2af3f1ee1f82b2d25b0ab58aebf48a036e634c41c91eeb08f2251b75b35b35
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Diff for a single embedded archive entry that appears in both results.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EmbeddedDiff.Builder.class)
public record EmbeddedDiff(
    /**
     * Archive-relative path identifying this entry.
     */
    @JsonProperty("path") String path,
    /**
     * The recursive diff of the entry's extraction result.
     */
    @JsonProperty("diff") ExtractionDiff diff
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

private String path = "";
private ExtractionDiff diff = null;

        /** Sets the path field. */
        @JsonProperty("path")
        public Builder withPath(final String value) {
            this.path = value;
            return this;
        }

        /** Sets the diff field. */
        @JsonProperty("diff")
        public Builder withDiff(final ExtractionDiff value) {
            this.diff = value;
            return this;
        }

        /** Builds the EmbeddedDiff instance. */
        public EmbeddedDiff build() {
            return new EmbeddedDiff(
                path,
                diff
            );
        }
    }
    // CPD-ON
}
