// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c0012448be4e00327689c0c05e2f511411c9fc99a4fc8f44745d064434b738f2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
package dev.kreuzberg;

import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Image metadata extracted from an image file.
 */
public record ExtractedImageMetadata(
    /**
     * Image width in pixels
     */
    int width,
    /**
     * Image height in pixels
     */
    int height,
    /**
     * Image format (e.g., "PNG", "JPEG")
     */
    String format,
    /**
     * EXIF data if available
     */
    @JsonProperty("exif_data") Map<String, String> exifData
) {
}
