// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c0012448be4e00327689c0c05e2f511411c9fc99a4fc8f44745d064434b738f2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Heading context for a chunk within a Markdown document.
 *
 * Contains the heading hierarchy from document root to this chunk's section.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = HeadingContext.Builder.class)
public record HeadingContext(@JsonProperty("headings") List<HeadingLevel> headings) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

private List<HeadingLevel> headings = List.of();

        /** Sets the headings field. */
        @JsonProperty("headings")
        public Builder withHeadings(final List<HeadingLevel> value) {
            this.headings = value;
            return this;
        }

        /** Builds the HeadingContext instance. */
        public HeadingContext build() {
            return new HeadingContext(
                headings
            );
        }
    }
    // CPD-ON
}
