// DO NOT EDIT - auto-generated by alef
// alef:hash:caebc3d131b03cb582c1cfce436a09b785978f3583c9aa2c5949daafccaf63ae
package dev.kreuzberg;

/**
 * An image manipulation operation (resize, decode, DPI conversion) failed.
 */
public class ImageProcessingException extends KreuzbergErrorException {
    /** Creates a new ImageProcessingException with the given message. */
    public ImageProcessingException(final String message) {
        super(message);
    }

    /** Creates a new ImageProcessingException with the given message and cause. */
    public ImageProcessingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
