// DO NOT EDIT - auto-generated by alef
// alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
package dev.kreuzberg;

/**
 * An image manipulation operation (resize, decode, DPI conversion) failed.
 */
public class ImageProcessingException extends KreuzbergErrorException {
    /** Creates a new ImageProcessingException with the given message. */
    public ImageProcessingException(final String message) {
        super(message);
    }

    /** Creates a new ImageProcessingException with the given message and cause. */
    public ImageProcessingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
