// DO NOT EDIT - auto-generated by alef
// alef:hash:7a2af3f1ee1f82b2d25b0ab58aebf48a036e634c41c91eeb08f2251b75b35b35
package dev.kreuzberg;

public class IoException extends KreuzbergErrorException {
    /** Creates a new IoException with the given message. */
    public IoException(final String message) {
        super(message);
    }

    /** Creates a new IoException with the given message and cause. */
    public IoException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
