// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a4b2535e507ad7d6891f9f696c62001bdc930272512ef1c9e8e151cb54027e5f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

/** Exception thrown by KreuzbergRs. */
@SuppressWarnings("checkstyle:LineLength")
public class KreuzbergRsException extends Exception {
    /** The error code. */
    private final int code;

    /** Creates a new KreuzbergRsException. */
    public KreuzbergRsException(final int code, final String message) {
        super(message);
        this.code = code;
    }

    /** Creates a new KreuzbergRsException with a cause. */
    public KreuzbergRsException(final String message, final Throwable cause) {
        super(message, cause);
        this.code = -1;
    }

    /** Returns the error code. */
    public int getCode() {
        return code;
    }
}
