// DO NOT EDIT - auto-generated by alef
// alef:hash:c5b9396b773dc8263bf55403ae885f5a2ddb930140b83455af3c7659da0f7ecd
package dev.kreuzberg;

public class LockPoisonedException extends KreuzbergErrorException {
    /** Creates a new LockPoisonedException with the given message. */
    public LockPoisonedException(final String message) {
        super(message);
    }

    /** Creates a new LockPoisonedException with the given message and cause. */
    public LockPoisonedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
