// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7a2af3f1ee1f82b2d25b0ab58aebf48a036e634c41c91eeb08f2251b75b35b35
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Rotation information for an OCR element.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = OcrRotation.Builder.class)
public record OcrRotation(
    /**
     * Rotation angle in degrees (0, 90, 180, 270 for PaddleOCR).
     */
    @JsonProperty("angle_degrees") double angleDegrees,
    /**
     * Confidence score for the rotation detection.
     */
    @Nullable @JsonProperty("confidence") Double confidence
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @JsonProperty("angle_degrees")
private double angleDegrees = 0.0;
private Double confidence = null;

        /** Sets the angleDegrees field. */
        @JsonProperty("angle_degrees")
        public Builder withAngleDegrees(final double value) {
            this.angleDegrees = value;
            return this;
        }

        /** Sets the confidence field. */
        @JsonProperty("confidence")
        public Builder withConfidence(final @Nullable double value) {
            this.confidence = value;
            return this;
        }

        /** Builds the OcrRotation instance. */
        public OcrRotation build() {
            return new OcrRotation(
                angleDegrees,
                confidence
            );
        }
    }
    // CPD-ON
}
