// DO NOT EDIT - auto-generated by alef
// alef:hash:a4b2535e507ad7d6891f9f696c62001bdc930272512ef1c9e8e151cb54027e5f
package dev.kreuzberg;

public class ParsingException extends KreuzbergErrorException {
    /** Creates a new ParsingException with the given message. */
    public ParsingException(final String message) {
        super(message);
    }

    /** Creates a new ParsingException with the given message and cause. */
    public ParsingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
