// DO NOT EDIT - auto-generated by alef
// alef:hash:c0012448be4e00327689c0c05e2f511411c9fc99a4fc8f44745d064434b738f2
package dev.kreuzberg;

public class PluginException extends KreuzbergErrorException {
    /** Creates a new PluginException with the given message. */
    public PluginException(final String message) {
        super(message);
    }

    /** Creates a new PluginException with the given message and cause. */
    public PluginException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
