// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Pixel-space bounding box of a QR code inside its source image.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = QrBoundingBox.Builder.class)
@SuppressWarnings("PMD")
public record QrBoundingBox(
    @JsonProperty("x") int x,
    @JsonProperty("y") int y,
    @JsonProperty("width") int width,
    @JsonProperty("height") int height
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

private int x = 0;
private int y = 0;
private int width = 0;
private int height = 0;

        /** Sets the x field. */
        @JsonProperty("x")
        public Builder withX(final int value) {
            this.x = value;
            return this;
        }

        /** Sets the y field. */
        @JsonProperty("y")
        public Builder withY(final int value) {
            this.y = value;
            return this;
        }

        /** Sets the width field. */
        @JsonProperty("width")
        public Builder withWidth(final int value) {
            this.width = value;
            return this;
        }

        /** Sets the height field. */
        @JsonProperty("height")
        public Builder withHeight(final int value) {
            this.height = value;
            return this;
        }

        /** Builds the QrBoundingBox instance. */
        public QrBoundingBox build() {
            return new QrBoundingBox(
                x,
                y,
                width,
                height
            );
        }
    }
    // CPD-ON
}
