// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Semantic classification of a tracked change.
 */
@SuppressWarnings("PMD")
public enum RevisionKind {
    /**
     * Text or content was inserted.
     */
    Insertion("insertion"),
    /**
     * Text or content was deleted.
     */
    Deletion("deletion"),
    /**
     * Run-level formatting (font, size, colour, …) was changed.
     */
    FormatChange("format_change"),
    /**
     * A reviewer comment or annotation.
     */
    Comment("comment");


    /** The string value. */
    private final String value;

    RevisionKind(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static RevisionKind fromValue(final String value) {
        for (RevisionKind e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown RevisionKind value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
