// DO NOT EDIT - auto-generated by alef
// alef:hash:caebc3d131b03cb582c1cfce436a09b785978f3583c9aa2c5949daafccaf63ae
package dev.kreuzberg;

/**
 * The document's MIME type is not supported by any registered extractor.
 */
public class UnsupportedFormatException extends KreuzbergErrorException {
    /** Creates a new UnsupportedFormatException with the given message. */
    public UnsupportedFormatException(final String message) {
        super(message);
    }

    /** Creates a new UnsupportedFormatException with the given message and cause. */
    public UnsupportedFormatException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
