# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require_relative "kreuzberg/version"
require_relative "kreuzberg/native"

# Top-level namespace for the Kreuzberg Ruby binding.
#
# All type and function symbols are re-exported from the native extension
# loaded via `require_relative "kreuzberg/native"`. See
# {file:README.md} for usage examples and the upstream documentation
# for the full API reference.
module Kreuzberg
  # Re-export all types and functions from native extension
end
