# Generated by alef. Do not edit by hand.
# alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
# Keep generated public API for consumers using R8/ProGuard.
-keep class dev.kreuzberg.** { *; }
