// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:41c3ace4b75f4de13ce67bb8487961322a3576c7b8ec3667a6687a12c59bf1a6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Hardware acceleration configuration for ONNX Runtime models.
 *
 * Controls which execution provider (CPU, CoreML, CUDA, TensorRT) is used
 * for inference in layout detection and embedding generation.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record AccelerationConfig(
    /**
     * Execution provider to use for ONNX inference.
     */
    ExecutionProviderType provider,
    /**
     * GPU device ID (for CUDA/TensorRT). Ignored for CPU/CoreML/Auto.
     */
    @JsonProperty("device_id") int deviceId
) {

    /**
     * Parse a {@code AccelerationConfig} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException if the JSON cannot be deserialised.
     */
    public static AccelerationConfig fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, AccelerationConfig.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse AccelerationConfig from JSON: " + e.getMessage(), e);
        }
    }
}
