// DO NOT EDIT - auto-generated by alef
// alef:hash:04f92dcfca2a624ebdef3d2dd11f39fca2b62c803777837d8ad0b9413bfb6373
package dev.kreuzberg;

public class IoException extends KreuzbergErrorException {
    /** Creates a new IoException with the given message. */
    public IoException(final String message) {
        super(message);
    }

    /** Creates a new IoException with the given message and cause. */
    public IoException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
