// DO NOT EDIT - auto-generated by alef
// alef:hash:6783b7a10b189d0de32dc851af3911528a52c87bcbf5aef589fd4771e21c4b0b
package dev.kreuzberg;

public class MissingDependencyException extends KreuzbergErrorException {
    /** Creates a new MissingDependencyException with the given message. */
    public MissingDependencyException(final String message) {
        super(message);
    }

    /** Creates a new MissingDependencyException with the given message and cause. */
    public MissingDependencyException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
