// DO NOT EDIT - auto-generated by alef
// alef:hash:222c1bd4be8c1548d4e4844196ea31d0839ec06ebefcad967dd3a90b4a3972a7
package dev.kreuzberg;

public class OcrException extends KreuzbergErrorException {
    /** Creates a new OcrException with the given message. */
    public OcrException(final String message) {
        super(message);
    }

    /** Creates a new OcrException with the given message and cause. */
    public OcrException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
