// DO NOT EDIT - auto-generated by alef
// alef:hash:6a1c27bf8267677925cc6e7909f9115933518bf21ce15ca407f74cdde80766fa
package dev.kreuzberg;

public class ParsingException extends KreuzbergErrorException {
    /** Creates a new ParsingException with the given message. */
    public ParsingException(final String message) {
        super(message);
    }

    /** Creates a new ParsingException with the given message and cause. */
    public ParsingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
