// DO NOT EDIT - auto-generated by alef
// alef:hash:9008681afa6ab6b825425e75829258abea260beac1367a5cb0c428e52e385fcd
package dev.kreuzberg;

public class SerializationException extends KreuzbergErrorException {
    /** Creates a new SerializationException with the given message. */
    public SerializationException(final String message) {
        super(message);
    }

    /** Creates a new SerializationException with the given message and cause. */
    public SerializationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
