// DO NOT EDIT - auto-generated by alef
// alef:hash:de13e821c8c3c9f09ad0b63245c7a1bbea836cce70e0835086844efe691c6f00
package dev.kreuzberg;

public class TimeoutException extends KreuzbergErrorException {
    /** Creates a new TimeoutException with the given message. */
    public TimeoutException(final String message) {
        super(message);
    }

    /** Creates a new TimeoutException with the given message and cause. */
    public TimeoutException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
