// DO NOT EDIT - auto-generated by alef
// alef:hash:19ef9aaee63f8d3a856ab093ea2198a7dd837bdd6349f4f06b000428ea3ce48f
package dev.kreuzberg;

public class UnsupportedFormatException extends KreuzbergErrorException {
    /** Creates a new UnsupportedFormatException with the given message. */
    public UnsupportedFormatException(final String message) {
        super(message);
    }

    /** Creates a new UnsupportedFormatException with the given message and cause. */
    public UnsupportedFormatException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
