# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dd68e758bf419eaf320bbb80df9c392b28136b4859b698c0a8064cef3c034eb4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ArchiveEntry do
  @moduledoc """
  A single file extracted from an archive.

  When archives (ZIP, TAR, 7Z, GZIP) are extracted with recursive extraction
  enabled, each processable file produces its own full `ExtractionResult`.
  """

  @typedoc "A single file extracted from an archive."
  @type t :: %__MODULE__{
          path: String.t() | nil,
          mime_type: String.t() | nil,
          result: map()
        }

  defstruct path: nil,
            mime_type: nil,
            result: nil
end
