# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a4b2535e507ad7d6891f9f696c62001bdc930272512ef1c9e8e151cb54027e5f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.BBox do
  @moduledoc "Bounding box in original image coordinates (x1, y1) top-left, (x2, y2) bottom-right."

  @typedoc "Bounding box in original image coordinates (x1, y1) top-left, (x2, y2) bottom-right."
  @type t :: %__MODULE__{
          x1: float(),
          y1: float(),
          x2: float(),
          y2: float()
        }

  defstruct x1: 0.0,
            y1: 0.0,
            x2: 0.0,
            y2: 0.0
end
