# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c5b9396b773dc8263bf55403ae885f5a2ddb930140b83455af3c7659da0f7ecd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.BBox do
  @moduledoc "Bounding box in original image coordinates (x1, y1) top-left, (x2, y2) bottom-right."

  @typedoc "Bounding box in original image coordinates (x1, y1) top-left, (x2, y2) bottom-right."
  @type t :: %__MODULE__{
          x1: float(),
          y1: float(),
          x2: float(),
          y2: float()
        }

  defstruct x1: 0.0,
            y1: 0.0,
            x2: 0.0,
            y2: 0.0
end
