# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dcd53c1ffa1fdf50991f98dc8edf67b04678a71573693591a825a04b7fe95e79
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.BatchFileItem do
  @moduledoc """
  Batch item for file extraction.

  Used with `batch_extract_files` and `batch_extract_files_sync`
  to represent a single file in a batch extraction job.
  """

  @typedoc "Batch item for file extraction."
  @type t :: %__MODULE__{
          path: String.t() | nil,
          config: map() | nil
        }

  defstruct path: nil,
            config: nil
end
