# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c5b9396b773dc8263bf55403ae885f5a2ddb930140b83455af3c7659da0f7ecd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.BatchBytesItem do
  @moduledoc """
  Batch item for byte array extraction.

  Used with `batch_extract_bytes` and `batch_extract_bytes_sync`
  to represent a single item in a batch extraction job.
  """

  @typedoc "Batch item for byte array extraction."
  @type t :: %__MODULE__{
          content: binary(),
          mime_type: String.t() | nil,
          config: map() | nil
        }

  defstruct content: <<>>,
            mime_type: nil,
            config: nil
end
