# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7a2af3f1ee1f82b2d25b0ab58aebf48a036e634c41c91eeb08f2251b75b35b35
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.CacheStats do
  @moduledoc false

  @type t :: %__MODULE__{
          total_files: non_neg_integer(),
          total_size_mb: float(),
          available_space_mb: float(),
          oldest_file_age_days: float(),
          newest_file_age_days: float()
        }

  defstruct total_files: 0,
            total_size_mb: 0.0,
            available_space_mb: 0.0,
            oldest_file_age_days: 0.0,
            newest_file_age_days: 0.0
end
