# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7a2af3f1ee1f82b2d25b0ab58aebf48a036e634c41c91eeb08f2251b75b35b35
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.CodeContentMode do
  @moduledoc """
  Content rendering mode for code extraction.

  Controls how extracted code content is represented in the `content` field
  of `ExtractionResult`.
  """

  @typedoc "Content rendering mode for code extraction."
  @type t :: :chunks | :raw | :structure

  @chunks :chunks
  @raw :raw
  @structure :structure

  @doc "Use TSLP semantic chunks as content (default)."
  @spec chunks() :: t()
  def chunks, do: @chunks
  @doc "Use raw source code as content."
  @spec raw() :: t()
  def raw, do: @raw
  @doc "Emit function/class headings + docstrings (no code bodies)."
  @spec structure() :: t()
  def structure, do: @structure
end
