# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c0012448be4e00327689c0c05e2f511411c9fc99a4fc8f44745d064434b738f2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.CodeContentMode do
  @moduledoc """
  Content rendering mode for code extraction.

  Controls how extracted code content is represented in the `content` field
  of `ExtractionResult`.
  """

  @typedoc "Content rendering mode for code extraction."
  @type t :: :chunks | :raw | :structure

  @chunks :chunks
  @raw :raw
  @structure :structure

  @doc "Use TSLP semantic chunks as content (default)."
  @spec chunks() :: t()
  def chunks, do: @chunks
  @doc "Use raw source code as content."
  @spec raw() :: t()
  def raw, do: @raw
  @doc "Emit function/class headings + docstrings (no code bodies)."
  @spec structure() :: t()
  def structure, do: @structure
end
