# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2ff29038011095afb3d7eb8a09db81e45782cb56105ffc3ad1d768578b86fa35
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ContentLayer do
  @moduledoc """
  Content layer classification for document nodes.

  Replaces separate body/furniture arrays with per-node granularity.
  """

  @typedoc "Content layer classification for document nodes."
  @type t :: :body | :header | :footer | :footnote

  @body :body
  @header :header
  @footer :footer
  @footnote :footnote

  @doc "Main document body content."
  @spec body() :: t()
  def body, do: @body
  @doc "Page/section header (running header)."
  @spec header() :: t()
  def header, do: @header
  @doc "Page/section footer (running footer)."
  @spec footer() :: t()
  def footer, do: @footer
  @doc "Footnote content."
  @spec footnote() :: t()
  def footnote, do: @footnote
end
