# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a4b2535e507ad7d6891f9f696c62001bdc930272512ef1c9e8e151cb54027e5f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DiffLine do
  @moduledoc """
  A single line in a unified-diff hunk.

  Defined here (rather than only in `crate::diff`) so `RevisionDelta` can
  reference it unconditionally, without requiring the `diff` Cargo feature.
  `crate::diff` re-exports this type verbatim.
  """

  @typedoc "A single line in a unified-diff hunk."
  @type t :: term()

  @typedoc "Unchanged context line."
  @type context :: %{type: :context, value: String.t()}
  @typedoc "Line added in the \"after\" version."
  @type added :: %{type: :added, value: String.t()}
  @typedoc "Line removed from the \"before\" version."
  @type removed :: %{type: :removed, value: String.t()}
end
