# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2ff29038011095afb3d7eb8a09db81e45782cb56105ffc3ad1d768578b86fa35
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DjotImage do
  @moduledoc "Image element in Djot."

  @typedoc "Image element in Djot."
  @type t :: %__MODULE__{
          src: String.t() | nil,
          alt: String.t() | nil,
          title: String.t() | nil,
          attributes: String.t() | nil
        }

  defstruct src: nil,
            alt: nil,
            title: nil,
            attributes: nil
end
