# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f13ab20f3179df77c009c13e23e5727d25243d915292e35a384f128576174af5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DjotImage do
  @moduledoc "Image element in Djot."

  @typedoc "Image element in Djot."
  @type t :: %__MODULE__{
          src: String.t() | nil,
          alt: String.t() | nil,
          title: String.t() | nil,
          attributes: String.t() | nil
        }

  defstruct src: nil,
            alt: nil,
            title: nil,
            attributes: nil
end
