# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a4b2535e507ad7d6891f9f696c62001bdc930272512ef1c9e8e151cb54027e5f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DjotLink do
  @moduledoc "Link element in Djot."

  @typedoc "Link element in Djot."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          text: String.t() | nil,
          title: String.t() | nil,
          attributes: String.t() | nil
        }

  defstruct url: nil,
            text: nil,
            title: nil,
            attributes: nil
end
