# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c5b9396b773dc8263bf55403ae885f5a2ddb930140b83455af3c7659da0f7ecd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ElementMetadata do
  @moduledoc "Metadata for a semantic element."

  @typedoc "Metadata for a semantic element."
  @type t :: %__MODULE__{
          page_number: non_neg_integer() | nil,
          filename: String.t() | nil,
          coordinates: map() | nil,
          element_index: non_neg_integer() | nil,
          additional: map()
        }

  defstruct page_number: nil,
            filename: nil,
            coordinates: nil,
            element_index: nil,
            additional: %{}
end
