# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fb6a96065acce180b509a42a2776f53d7bb99b6e66bce108b1d527e3cfec1099
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmailMetadata do
  @moduledoc """
  Email metadata extracted from .eml and .msg files.

  Includes sender/recipient information, message ID, and attachment list.
  """

  @typedoc "Email metadata extracted from .eml and .msg files."
  @type t :: %__MODULE__{
          from_email: String.t() | nil,
          from_name: String.t() | nil,
          to_emails: [String.t()],
          cc_emails: [String.t()],
          bcc_emails: [String.t()],
          message_id: String.t() | nil,
          attachments: [String.t()]
        }

  defstruct from_email: nil,
            from_name: nil,
            to_emails: [],
            cc_emails: [],
            bcc_emails: [],
            message_id: nil,
            attachments: []
end
