# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c0012448be4e00327689c0c05e2f511411c9fc99a4fc8f44745d064434b738f2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.EmbeddedFile do
  @moduledoc "Embedded file descriptor extracted from the PDF name tree."

  @typedoc "Embedded file descriptor extracted from the PDF name tree."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          data: binary(),
          mime_type: String.t() | nil
        }

  defstruct name: nil,
            data: <<>>,
            mime_type: nil
end
