# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.EmbeddedChanges do
  @moduledoc "Changes to embedded archive children between two results."

  @typedoc "Changes to embedded archive children between two results."
  @type t :: %__MODULE__{
          added: [map()],
          removed: [map()],
          changed: [map()]
        }

  defstruct added: [],
            removed: [],
            changed: []
end
