# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.EmbeddedFile do
  @moduledoc "Embedded file descriptor extracted from the PDF name tree."

  @typedoc "Embedded file descriptor extracted from the PDF name tree."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          data: binary(),
          compressed_size: non_neg_integer(),
          mime_type: String.t() | nil
        }

  defstruct name: nil,
            data: <<>>,
            compressed_size: 0,
            mime_type: nil
end
