# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c0012448be4e00327689c0c05e2f511411c9fc99a4fc8f44745d064434b738f2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.EpubMetadata do
  @moduledoc "EPUB metadata (Dublin Core extensions)."

  @typedoc "EPUB metadata (Dublin Core extensions)."
  @type t :: %__MODULE__{
          coverage: String.t() | nil,
          dc_format: String.t() | nil,
          relation: String.t() | nil,
          source: String.t() | nil,
          dc_type: String.t() | nil,
          cover_image: String.t() | nil
        }

  defstruct coverage: nil,
            dc_format: nil,
            relation: nil,
            source: nil,
            dc_type: nil,
            cover_image: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
