# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dcd53c1ffa1fdf50991f98dc8edf67b04678a71573693591a825a04b7fe95e79
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.ExcelMetadata do
  @moduledoc """
  Excel/spreadsheet format metadata.

  Identifies the document as a spreadsheet source via the `FormatMetadata::Excel`
  discriminant. Sheet count and sheet names are stored inside this struct.
  """

  @typedoc "Excel/spreadsheet format metadata."
  @type t :: %__MODULE__{
          sheet_count: non_neg_integer() | nil,
          sheet_names: [String.t()] | nil
        }

  defstruct sheet_count: nil,
            sheet_names: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
