# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a4b2535e507ad7d6891f9f696c62001bdc930272512ef1c9e8e151cb54027e5f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractionDiff do
  @moduledoc "The complete diff between two `ExtractionResult` values."

  @typedoc "The complete diff between two `ExtractionResult` values."
  @type t :: %__MODULE__{
          content_diff: [map()],
          tables_added: [map()],
          tables_removed: [map()],
          tables_changed: [map()],
          metadata_changed: String.t() | nil,
          embedded_changes: map()
        }

  defstruct content_diff: [],
            tables_added: [],
            tables_removed: [],
            tables_changed: [],
            metadata_changed: nil,
            embedded_changes: nil
end
