# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dcd53c1ffa1fdf50991f98dc8edf67b04678a71573693591a825a04b7fe95e79
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.ExtractedImageMetadata do
  @moduledoc "Image metadata extracted from an image file."

  @typedoc "Image metadata extracted from an image file."
  @type t :: %__MODULE__{
          width: non_neg_integer(),
          height: non_neg_integer(),
          format: String.t() | nil,
          exif_data: map()
        }

  defstruct width: 0,
            height: 0,
            format: nil,
            exif_data: %{}
end
