# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dcd53c1ffa1fdf50991f98dc8edf67b04678a71573693591a825a04b7fe95e79
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.FracType do
  @moduledoc false

  @type t :: :bar | :no_bar | :linear | :skewed

  @bar :bar
  @no_bar :no_bar
  @linear :linear
  @skewed :skewed

  @spec bar() :: t()
  def bar, do: @bar
  @spec no_bar() :: t()
  def no_bar, do: @no_bar
  @spec linear() :: t()
  def linear, do: @linear
  @spec skewed() :: t()
  def skewed, do: @skewed
end
