# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c5b9396b773dc8263bf55403ae885f5a2ddb930140b83455af3c7659da0f7ecd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.HeadingContext do
  @moduledoc """
  Heading context for a chunk within a Markdown document.

  Contains the heading hierarchy from document root to this chunk's section.
  """

  @typedoc "Heading context for a chunk within a Markdown document."
  @type t :: %__MODULE__{
          headings: [map()]
        }

  defstruct headings: []
end
