# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.HierarchicalBlock do
  @moduledoc """
  A text block with hierarchy level assignment.

  Represents a block of text with semantic heading information extracted from
  font size clustering and hierarchical analysis.
  """

  @typedoc "A text block with hierarchy level assignment."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          font_size: float(),
          level: String.t() | nil
        }

  defstruct text: nil,
            font_size: 0.0,
            level: nil
end
