# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c04e2d4279be756ba551c3a3e7b168642915705c2f2b7ad7841240ac0778f171
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HtmlOutputConfig do
  @moduledoc """
  Configuration for styled HTML output.

  When set on [`ExtractionConfig::html_output`] alongside
  `output_format = OutputFormat::Html`, the pipeline builds a
  [`StyledHtmlRenderer`](crate::rendering::StyledHtmlRenderer) instead of
  the plain comrak-based renderer.

  # Example

  ```rust
  use kreuzberg::core::config::{HtmlOutputConfig, HtmlTheme};

  let config = HtmlOutputConfig {
      theme: HtmlTheme::GitHub,
      css: Some(".kb-p { font-size: 1.1rem; }".to_string()),
      ..Default::default()
  };
  ```
  """

  @typedoc "Configuration for styled HTML output."
  @type t :: %__MODULE__{
          css: String.t() | nil,
          css_file: String.t() | nil,
          theme: String.t() | nil,
          class_prefix: String.t() | nil,
          embed_css: boolean()
        }

  defstruct css: nil,
            css_file: nil,
            theme: :unstyled,
            class_prefix: nil,
            embed_css: true
end
