# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c0012448be4e00327689c0c05e2f511411c9fc99a4fc8f44745d064434b738f2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.InlineElement do
  @moduledoc """
  Inline element within a block.

  Represents text with formatting, links, images, etc.
  """

  @typedoc "Inline element within a block."
  @type t :: %__MODULE__{
          element_type: String.t() | nil,
          content: String.t() | nil,
          attributes: String.t() | nil,
          metadata: map() | nil
        }

  defstruct element_type: :text,
            content: nil,
            attributes: nil,
            metadata: nil
end
