# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.LinkMetadata do
  @moduledoc "Link element metadata."

  @typedoc "Link element metadata."
  @type t :: %__MODULE__{
          href: String.t() | nil,
          text: String.t() | nil,
          title: String.t() | nil,
          link_type: String.t() | nil,
          rel: [String.t()]
        }

  defstruct href: nil,
            text: nil,
            title: nil,
            link_type: :anchor,
            rel: []
end
