# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c0012448be4e00327689c0c05e2f511411c9fc99a4fc8f44745d064434b738f2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.LinkType do
  @moduledoc "Link type classification."

  @typedoc "Link type classification."
  @type t :: :anchor | :internal | :external | :email | :phone | :other

  @anchor :anchor
  @internal :internal
  @external :external
  @email :email
  @phone :phone
  @other :other

  @doc "Anchor link (#section)"
  @spec anchor() :: t()
  def anchor, do: @anchor
  @doc "Internal link (same domain)"
  @spec internal() :: t()
  def internal, do: @internal
  @doc "External link (different domain)"
  @spec external() :: t()
  def external, do: @external
  @doc "Email link (mailto:)"
  @spec email() :: t()
  def email, do: @email
  @doc "Phone link (tel:)"
  @spec phone() :: t()
  def phone, do: @phone
  @doc "Other link type"
  @spec other() :: t()
  def other, do: @other
end
