# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c0012448be4e00327689c0c05e2f511411c9fc99a4fc8f44745d064434b738f2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.LinkMetadata do
  @moduledoc "Link element metadata."

  @typedoc "Link element metadata."
  @type t :: %__MODULE__{
          href: String.t() | nil,
          text: String.t() | nil,
          title: String.t() | nil,
          link_type: String.t() | nil,
          rel: [String.t()],
          attributes: [[String.t()]]
        }

  defstruct href: nil,
            text: nil,
            title: nil,
            link_type: :anchor,
            rel: [],
            attributes: []
end
