# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dcd53c1ffa1fdf50991f98dc8edf67b04678a71573693591a825a04b7fe95e79
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.ListType do
  @moduledoc "Type of list detection."

  @typedoc "Type of list detection."
  @type t :: :bullet | :numbered | :lettered | :indented

  @bullet :bullet
  @numbered :numbered
  @lettered :lettered
  @indented :indented

  @doc "Bullet points (-, *, •, etc.)"
  @spec bullet() :: t()
  def bullet, do: @bullet
  @doc "Numbered lists (1., 2., etc.)"
  @spec numbered() :: t()
  def numbered, do: @numbered
  @doc "Lettered lists (a., b., A., B., etc.)"
  @spec lettered() :: t()
  def lettered, do: @lettered
  @doc "Indented items"
  @spec indented() :: t()
  def indented, do: @indented
end
