# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7a2af3f1ee1f82b2d25b0ab58aebf48a036e634c41c91eeb08f2251b75b35b35
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.LlmUsage do
  @moduledoc """
  Token usage and cost data for a single LLM call made during extraction.

  Populated when VLM OCR, structured extraction, or LLM-based embeddings
  are used. Multiple entries may be present when multiple LLM calls occur
  within one extraction (e.g. VLM OCR + structured extraction).
  """

  @typedoc "Token usage and cost data for a single LLM call made during extraction."
  @type t :: %__MODULE__{
          model: String.t() | nil,
          source: String.t() | nil,
          input_tokens: non_neg_integer() | nil,
          output_tokens: non_neg_integer() | nil,
          total_tokens: non_neg_integer() | nil,
          estimated_cost: float() | nil,
          finish_reason: String.t() | nil
        }

  defstruct model: nil,
            source: nil,
            input_tokens: nil,
            output_tokens: nil,
            total_tokens: nil,
            estimated_cost: nil,
            finish_reason: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
