# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.NerConfig do
  @moduledoc "Configuration for the NER post-processor."

  @typedoc "Configuration for the NER post-processor."
  @type t :: %__MODULE__{
          backend: String.t() | nil,
          categories: [String.t() | nil],
          model: String.t() | nil,
          llm: map() | nil,
          custom_labels: [String.t()]
        }

  defstruct backend: :onnx,
            categories: [],
            model: nil,
            llm: nil,
            custom_labels: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
