# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7a2af3f1ee1f82b2d25b0ab58aebf48a036e634c41c91eeb08f2251b75b35b35
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.OcrElementLevel do
  @moduledoc """
  Hierarchical level of an OCR element.

  Maps to Tesseract's page segmentation hierarchy and provides
  equivalent semantics for PaddleOCR.
  """

  @typedoc "Hierarchical level of an OCR element."
  @type t :: :word | :line | :block | :page

  @word :word
  @line :line
  @block :block
  @page :page

  @doc "Individual word"
  @spec word() :: t()
  def word, do: @word
  @doc "Line of text (default for PaddleOCR)"
  @spec line() :: t()
  def line, do: @line
  @doc "Paragraph or text block"
  @spec block() :: t()
  def block, do: @block
  @doc "Page-level element"
  @spec page() :: t()
  def page, do: @page
end
