# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7a2af3f1ee1f82b2d25b0ab58aebf48a036e634c41c91eeb08f2251b75b35b35
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.OcrConfig do
  @moduledoc "OCR configuration."

  @typedoc "OCR configuration."
  @type t :: %__MODULE__{
          enabled: boolean(),
          backend: String.t() | nil,
          language: String.t() | nil,
          tesseract_config: map() | nil,
          output_format: String.t() | nil | nil,
          paddle_ocr_config: String.t() | nil,
          backend_options: String.t() | nil,
          element_config: map() | nil,
          quality_thresholds: map() | nil,
          pipeline: map() | nil,
          auto_rotate: boolean(),
          vlm_fallback: String.t() | nil,
          vlm_config: map() | nil,
          vlm_prompt: String.t() | nil,
          acceleration: map() | nil,
          tessdata_bytes: map() | nil
        }

  defstruct enabled: true,
            backend: nil,
            language: nil,
            tesseract_config: nil,
            output_format: nil,
            paddle_ocr_config: nil,
            backend_options: nil,
            element_config: nil,
            quality_thresholds: nil,
            pipeline: nil,
            auto_rotate: false,
            vlm_fallback: :disabled,
            vlm_config: nil,
            vlm_prompt: nil,
            acceleration: nil,
            tessdata_bytes: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
