# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8db0c85b74156fe66df2dbb9887ead15613d56b99a9d008fa45cd59944e760da
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrCacheStats do
  @moduledoc false

  @type t :: %__MODULE__{
          total_files: non_neg_integer(),
          total_size_mb: float()
        }

  defstruct total_files: 0,
            total_size_mb: 0.0
end
