# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dcd53c1ffa1fdf50991f98dc8edf67b04678a71573693591a825a04b7fe95e79
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.OcrPipelineStage do
  @moduledoc "A single backend stage in the OCR pipeline."

  @typedoc "A single backend stage in the OCR pipeline."
  @type t :: %__MODULE__{
          backend: String.t() | nil,
          priority: non_neg_integer(),
          language: String.t() | nil,
          tesseract_config: map() | nil,
          paddle_ocr_config: String.t() | nil,
          vlm_config: map() | nil,
          backend_options: String.t() | nil
        }

  defstruct backend: nil,
            priority: 0,
            language: nil,
            tesseract_config: nil,
            paddle_ocr_config: nil,
            vlm_config: nil,
            backend_options: nil
end
