# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a4b2535e507ad7d6891f9f696c62001bdc930272512ef1c9e8e151cb54027e5f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrRotation do
  @moduledoc "Rotation information for an OCR element."

  @typedoc "Rotation information for an OCR element."
  @type t :: %__MODULE__{
          angle_degrees: float(),
          confidence: float() | nil
        }

  defstruct angle_degrees: 0.0,
            confidence: nil
end
