# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2ff29038011095afb3d7eb8a09db81e45782cb56105ffc3ad1d768578b86fa35
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrTable do
  @moduledoc """
  Table detected via OCR.

  Represents a table structure recognized during OCR processing.
  """

  @typedoc "Table detected via OCR."
  @type t :: %__MODULE__{
          cells: [[String.t()]],
          markdown: String.t() | nil,
          page_number: non_neg_integer(),
          bounding_box: map() | nil
        }

  defstruct cells: [],
            markdown: nil,
            page_number: 0,
            bounding_box: nil
end
