# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.OcrPipelineConfig do
  @moduledoc """
  Multi-backend OCR pipeline with quality-based fallback.

  Backends are tried in priority order (highest first). After each backend
  produces output, quality is evaluated. If it meets `quality_thresholds.pipeline_min_quality`,
  the result is accepted. Otherwise the next backend is tried.
  """

  @typedoc "Multi-backend OCR pipeline with quality-based fallback."
  @type t :: %__MODULE__{
          stages: [map()],
          quality_thresholds: map()
        }

  defstruct stages: [],
            quality_thresholds: nil
end
