# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c0012448be4e00327689c0c05e2f511411c9fc99a4fc8f44745d064434b738f2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.PageUnitType do
  @moduledoc """
  Type of paginated unit in a document.

  Distinguishes between different types of "pages" (PDF pages, presentation slides, spreadsheet sheets).
  """

  @typedoc "Type of paginated unit in a document."
  @type t :: :page | :slide | :sheet

  @page :page
  @slide :slide
  @sheet :sheet

  @doc "Standard document pages (PDF, DOCX, images)"
  @spec page() :: t()
  def page, do: @page
  @doc "Presentation slides (PPTX, ODP)"
  @spec slide() :: t()
  def slide, do: @slide
  @doc "Spreadsheet sheets (XLSX, ODS)"
  @spec sheet() :: t()
  def sheet, do: @sheet
end
