# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c0012448be4e00327689c0c05e2f511411c9fc99a4fc8f44745d064434b738f2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.PdfConfig do
  @moduledoc "PDF-specific configuration."

  @typedoc "PDF-specific configuration."
  @type t :: %__MODULE__{
          extract_images: boolean(),
          extract_tables: boolean(),
          passwords: [String.t()] | nil,
          extract_metadata: boolean(),
          hierarchy: map() | nil,
          extract_annotations: boolean(),
          top_margin_fraction: float() | nil,
          bottom_margin_fraction: float() | nil,
          allow_single_column_tables: boolean(),
          ocr_inline_images: boolean()
        }

  defstruct extract_images: false,
            extract_tables: true,
            passwords: nil,
            extract_metadata: true,
            hierarchy: nil,
            extract_annotations: false,
            top_margin_fraction: nil,
            bottom_margin_fraction: nil,
            allow_single_column_tables: false,
            ocr_inline_images: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
