# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ProcessingWarning do
  @moduledoc """
  A non-fatal warning from a processing pipeline stage.

  Captures errors from optional features that don't prevent extraction
  but may indicate degraded results.
  """

  @typedoc "A non-fatal warning from a processing pipeline stage."
  @type t :: %__MODULE__{
          source: String.t() | nil,
          message: String.t() | nil
        }

  defstruct source: nil,
            message: nil
end
