# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.QrCode do
  @moduledoc "One QR code decoded from an extracted image."

  @typedoc "One QR code decoded from an extracted image."
  @type t :: %__MODULE__{
          payload: String.t() | nil,
          confidence: float() | nil,
          bbox: map() | nil
        }

  defstruct payload: nil,
            confidence: nil,
            bbox: nil
end
