# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7a2af3f1ee1f82b2d25b0ab58aebf48a036e634c41c91eeb08f2251b75b35b35
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.RedactionStrategy do
  @moduledoc "Strategy applied when a PII match is rewritten."

  @typedoc "Strategy applied when a PII match is rewritten."
  @type t :: :mask | :hash | :token_replace | :drop

  @mask :mask
  @hash :hash
  @token_replace :token_replace
  @drop :drop

  @doc "Replace the matched span with a fixed mask token (default `\"[REDACTED]\"`)."
  @spec mask() :: t()
  def mask, do: @mask
  @doc "Replace with a SHA-256 hash of the original value (truncated to 16 hex chars). Lets downstream consumers do equality joins without recovering the source."
  @spec hash() :: t()
  def hash, do: @hash
  @doc "Replace with a per-category running token (`\"[PERSON_1]\"`, `\"[PERSON_2]\"`, …) so the same person referenced twice gets the same token within the document."
  @spec token_replace() :: t()
  def token_replace, do: @token_replace
  @doc "Delete the matched span entirely."
  @spec drop() :: t()
  def drop, do: @drop
end
