# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7a2af3f1ee1f82b2d25b0ab58aebf48a036e634c41c91eeb08f2251b75b35b35
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.RevisionAnchor do
  @moduledoc "Best-effort document location for a revision."

  @typedoc "Best-effort document location for a revision."
  @type t :: term()

  @typedoc "Body paragraph, identified by its zero-based index in the document flow."
  @type paragraph :: %{type: :paragraph, index: non_neg_integer()}
  @typedoc "Cell inside a table."
  @type table_cell :: %{type: :table_cell, row: non_neg_integer(), col: non_neg_integer(), table_index: non_neg_integer()}
  @typedoc "Page, identified by its zero-based index."
  @type page :: %{type: :page, index: non_neg_integer()}
  @typedoc "Presentation slide, identified by its zero-based index."
  @type slide :: %{type: :slide, index: non_neg_integer()}
  @typedoc "Spreadsheet cell or range, identified by sheet index and optional name."
  @type sheet :: %{type: :sheet, index: non_neg_integer(), name: String.t()}
end
