# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7a2af3f1ee1f82b2d25b0ab58aebf48a036e634c41c91eeb08f2251b75b35b35
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.StructuredData do
  @moduledoc "Structured data (Schema.org, microdata, RDFa) block."

  @typedoc "Structured data (Schema.org, microdata, RDFa) block."
  @type t :: %__MODULE__{
          data_type: String.t() | nil,
          raw_json: String.t() | nil,
          schema_type: String.t() | nil
        }

  defstruct data_type: :json_ld,
            raw_json: nil,
            schema_type: nil
end
