# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c0012448be4e00327689c0c05e2f511411c9fc99a4fc8f44745d064434b738f2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.SupportedFormat do
  @moduledoc """
  A supported document format entry.

  Represents a file extension and its corresponding MIME type that Kreuzberg can process.
  """

  @typedoc "A supported document format entry."
  @type t :: %__MODULE__{
          extension: String.t() | nil,
          mime_type: String.t() | nil
        }

  defstruct extension: nil,
            mime_type: nil
end
