# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c5b9396b773dc8263bf55403ae885f5a2ddb930140b83455af3c7659da0f7ecd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.TableCell do
  @moduledoc """
  Individual table cell with content and optional styling.

  Future extension point for rich table support with cell-level metadata.
  """

  @typedoc "Individual table cell with content and optional styling."
  @type t :: %__MODULE__{
          content: String.t() | nil,
          row_span: non_neg_integer(),
          col_span: non_neg_integer(),
          is_header: boolean()
        }

  defstruct content: nil,
            row_span: 0,
            col_span: 0,
            is_header: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
