# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c0012448be4e00327689c0c05e2f511411c9fc99a4fc8f44745d064434b738f2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.TextDirection do
  @moduledoc "Text direction enumeration for HTML documents."

  @typedoc "Text direction enumeration for HTML documents."
  @type t :: :ltr | :rtl | :auto

  @left_to_right :ltr
  @right_to_left :rtl
  @auto :auto

  @doc "Left-to-right text direction"
  @spec left_to_right() :: t()
  def left_to_right, do: @left_to_right
  @doc "Right-to-left text direction"
  @spec right_to_left() :: t()
  def right_to_left, do: @right_to_left
  @doc "Automatic text direction detection"
  @spec auto() :: t()
  def auto, do: @auto
end
