# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dcd53c1ffa1fdf50991f98dc8edf67b04678a71573693591a825a04b7fe95e79
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.TextMetadata do
  @moduledoc """
  Text/Markdown metadata.

  Extracted from plain text and Markdown files. Includes word counts and,
  for Markdown, structural elements like headers and links.
  """

  @typedoc "Text/Markdown metadata."
  @type t :: %__MODULE__{
          line_count: non_neg_integer(),
          word_count: non_neg_integer(),
          character_count: non_neg_integer(),
          headers: [String.t()] | nil,
          links: [[String.t()]] | nil,
          code_blocks: [[String.t()]] | nil
        }

  defstruct line_count: 0,
            word_count: 0,
            character_count: 0,
            headers: nil,
            links: nil,
            code_blocks: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
