# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.WhisperModel do
  @moduledoc """
  Supported Whisper model sizes.

  These map to published ONNX exports on Hugging Face (onnx-community or
  similar orgs). The actual filenames and repos are resolved inside the
  transcription engine.
  """

  @typedoc "Supported Whisper model sizes."
  @type t :: :tiny | :base | :small | :medium | :large_v3

  @tiny :tiny
  @base :base
  @small :small
  @medium :medium
  @large_v3 :large_v3

  @doc "~39 MB, fastest, lowest quality. Good default for development and CI."
  @spec tiny() :: t()
  def tiny, do: @tiny
  @doc "~74 MB, reasonable quality/speed tradeoff."
  @spec base() :: t()
  def base, do: @base
  @doc "~244 MB, better accuracy."
  @spec small() :: t()
  def small, do: @small
  @doc "~769 MB, high quality (slower, more memory)."
  @spec medium() :: t()
  def medium, do: @medium
  @doc "~1550 MB, best quality (large-v3). Use only when latency is acceptable."
  @spec large_v3() :: t()
  def large_v3, do: @large_v3
end
