# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.XlsxAppProperties do
  @moduledoc """
  Application properties from docProps/app.xml for XLSX

  Contains Excel-specific document metadata.
  """

  @typedoc "Application properties from docProps/app.xml for XLSX"
  @type t :: %__MODULE__{
          application: String.t() | nil,
          app_version: String.t() | nil,
          doc_security: integer() | nil,
          scale_crop: boolean() | nil,
          links_up_to_date: boolean() | nil,
          shared_doc: boolean() | nil,
          hyperlinks_changed: boolean() | nil,
          company: String.t() | nil,
          worksheet_names: [String.t()]
        }

  defstruct application: nil,
            app_version: nil,
            doc_security: nil,
            scale_crop: nil,
            links_up_to_date: nil,
            shared_doc: nil,
            hyperlinks_changed: nil,
            company: nil,
            worksheet_names: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
