# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dcd53c1ffa1fdf50991f98dc8edf67b04678a71573693591a825a04b7fe95e79
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.XmlMetadata do
  @moduledoc """
  XML metadata extracted during XML parsing.

  Provides statistics about XML document structure.
  """

  @typedoc "XML metadata extracted during XML parsing."
  @type t :: %__MODULE__{
          element_count: non_neg_integer(),
          unique_elements: [String.t()]
        }

  defstruct element_count: 0,
            unique_elements: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
