# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7a2af3f1ee1f82b2d25b0ab58aebf48a036e634c41c91eeb08f2251b75b35b35
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code

#' @useDynLib kreuzberg, .registration = TRUE
NULL
