// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:62d076de56bb9a3edc72fe57459946cbc47660c41b3ae1d7b2adf8829d19cc0d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

import { describe, expect, it } from "vitest";
import {
  extractFile,
  detectMimeTypeFromBytes,
  getExtensionsForMime,
  WasmContentFilterConfig,
  WasmSecurityLimits,
  WasmTesseractConfig,
  WasmEmailConfig,
  WasmPageConfig,
  WasmKeywordConfig,
  WasmOcrElementConfig,
  WasmLlmConfig,
  WasmTokenReductionOptions,
  WasmAccelerationConfig,
  WasmLayoutDetectionConfig,
  WasmOcrConfig,
  WasmImagePreprocessingConfig,
  WasmEmbeddingConfig,
  WasmChunkingConfig,
  WasmImageExtractionConfig,
  WasmTreeSitterProcessConfig,
  WasmTreeSitterConfig,
  WasmStructuredExtractionConfig,
  WasmOcrPipelineStage,
  WasmOcrPipelineConfig,
  WasmOcrQualityThresholds,
  WasmHierarchyConfig,
  WasmYakeParams,
  WasmPdfConfig,
  WasmHtmlOutputConfig,
  WasmLanguageDetectionConfig,
  WasmPostProcessorConfig,
  WasmRakeParams,
} from "kreuzberg";
function _alefE2eText(value: unknown): string {
  return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
  if (item == null || typeof item !== "object") {
    return [_alefE2eText(item)];
  }
  const record = item as Record<string, unknown>;
  const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
  return [
    _alefE2eText(item),
    _alefE2eText(record.kind),
    _alefE2eText(record.name),
    _alefE2eText(record.source),
    _alefE2eText(record.alias),
    _alefE2eText(record.text),
    _alefE2eText(record.signature),
    itemsText,
  ];
}

describe("detection", () => {
  it("detect_mime_bytes_html: Detect HTML MIME from bytes", async () => {
    const _content_content = await (await import("node:fs/promises")).readFile("html/html.html");
    detectMimeTypeFromBytes(_content_content);
  });
  it("detect_mime_bytes_pdf: Detect PDF MIME type from bytes", async () => {
    const _content_content = await (await import("node:fs/promises")).readFile("pdf/fake_memo.pdf");
    detectMimeTypeFromBytes(_content_content);
  });
  it("detect_mime_bytes_png: Detect PNG MIME type from bytes", async () => {
    const _content_content = await (
      await import("node:fs/promises")
    ).readFile("images/test_hello_world.png");
    detectMimeTypeFromBytes(_content_content);
  });
  it("get_extensions_unknown_mime: get_extensions unknown MIME", async () => {
    await expect(async () => {
      await getExtensionsForMime("application/x-totally-unknown");
    }).rejects.toThrow();
  });
});
