// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9505da5931222bfb3f60667b987f1c3a3b5c8ca7aabbd7c19d6845c16ead8d50
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

import { describe, expect, it } from "vitest";
import {
  extractFile,
  clearRenderers,
  listRenderers,
  WasmContentFilterConfig,
  WasmKeywordConfig,
  WasmTreeSitterProcessConfig,
  WasmLanguageDetectionConfig,
  WasmPostProcessorConfig,
  WasmPageConfig,
  WasmRakeParams,
  WasmOcrPipelineConfig,
  WasmOcrPipelineStage,
  WasmHierarchyConfig,
  WasmLlmConfig,
  WasmAccelerationConfig,
  WasmTreeSitterConfig,
  WasmOcrConfig,
  WasmYakeParams,
  WasmImageExtractionConfig,
  WasmSecurityLimits,
  WasmLayoutDetectionConfig,
  WasmHtmlOutputConfig,
  WasmPdfConfig,
  WasmStructuredExtractionConfig,
  WasmEmbeddingConfig,
  WasmTesseractConfig,
  WasmOcrElementConfig,
  WasmEmailConfig,
  WasmTokenReductionOptions,
  WasmOcrQualityThresholds,
  WasmChunkingConfig,
  WasmImagePreprocessingConfig,
} from "kreuzberg";
function _alefE2eText(value: unknown): string {
  return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
  if (item == null || typeof item !== "object") {
    return [_alefE2eText(item)];
  }
  const record = item as Record<string, unknown>;
  const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
  return [
    _alefE2eText(item),
    _alefE2eText(record.kind),
    _alefE2eText(record.name),
    _alefE2eText(record.source),
    _alefE2eText(record.alias),
    _alefE2eText(record.text),
    _alefE2eText(record.signature),
    itemsText,
  ];
}

describe("renderer_management", () => {
  it("renderers_clear: Clear all renderers and verify list is empty", () => {
    const result = clearRenderers();
    expect(result.length).toBe(0);
  });
  it("renderers_list: List all registered renderers", () => {
    listRenderers();
  });
});
