# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7a2af3f1ee1f82b2d25b0ab58aebf48a036e634c41c91eeb08f2251b75b35b35
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'code' do
  it 'code_shebang_detection: Test language detection from shebang line via bytes input' do
    result = Kreuzberg.extract_file_sync('code/script.sh', 'text/x-source-code')
    expect(result.mime_type.to_s.strip).to eq('text/x-source-code'.strip)
    expect(result.content.length).to be >= 10
    expect(result.content.to_s).to include('build')
    expect(result.content.to_s).to include('clean')

  end
end
