# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c0012448be4e00327689c0c05e2f511411c9fc99a4fc8f44745d064434b738f2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'code' do
  it 'code_shebang_detection: Test language detection from shebang line via bytes input' do
    result = Kreuzberg.extract_file_sync('code/script.sh', 'text/x-source-code')
    expect(result.mime_type.to_s.strip).to eq('text/x-source-code'.strip)
    expect(result.content.length).to be >= 10
    expect(result.content.to_s).to include('build')
    expect(result.content.to_s).to include('clean')

  end
end
