# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'document_extractor_management' do
  it 'document_extractors_clear: Clear all document extractors and verify list is empty' do
    Kreuzberg.clear_document_extractors()

  end

  it 'extractors_list: List all registered document extractors' do
    result = Kreuzberg.list_document_extractors()

    expect(result).not_to be_nil
  end
end
