# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:caebc3d131b03cb582c1cfce436a09b785978f3583c9aa2c5949daafccaf63ae
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'embedding_backend_management' do
  it 'embedding_backends_clear: Clear all embedding backends and verify list is empty' do
    Kreuzberg.clear_embedding_backends()

  end

  it 'embedding_backends_list: List all registered embedding backends' do
    result = Kreuzberg.list_embedding_backends()

    expect(result).not_to be_nil
  end
end
