# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a4b2535e507ad7d6891f9f696c62001bdc930272512ef1c9e8e151cb54027e5f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'embedding_backend_management' do
  it 'embedding_backends_clear: Clear all embedding backends and verify list is empty' do
    Kreuzberg.clear_embedding_backends()

  end

  it 'embedding_backends_list: List all registered embedding backends' do
    result = Kreuzberg.list_embedding_backends()

    expect(result).not_to be_nil
  end
end
