# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'ocr_backend_management' do
  it 'ocr_backends_clear: Clear all OCR backends and verify list is empty' do
    Kreuzberg.clear_ocr_backends()

  end

  it 'ocr_backends_list: List all registered OCR backends' do
    result = Kreuzberg.list_ocr_backends()

    expect(result).not_to be_nil
  end

  it 'ocr_backends_unregister: Unregister nonexistent OCR backend gracefully' do
    Kreuzberg.unregister_ocr_backend('nonexistent-backend-xyz')

  end
end
