# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:30840e27833ba063942ba67f7fc9dbc7d65b751bbf474e7bacf6ec4e495fc44e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'plugin_api' do
  it 'register_document_extractor_trait_bridge: register_document_extractor: trait bridge' do
    result = Kreuzberg.register_document_extractor({ 'extractor' => { 'name' => 'test-extractor', 'type' => 'test' } })

    expect(result).not_to be_nil
  end

  it 'register_embedding_backend_trait_bridge: register_embedding_backend: trait bridge' do
    result = Kreuzberg.register_embedding_backend({ 'backend' => { 'name' => 'test-embedding-backend', 'type' => 'test' } })

    expect(result).not_to be_nil
  end

  it 'register_ocr_backend_trait_bridge: register_ocr_backend: trait bridge' do
    result = Kreuzberg.register_ocr_backend({ 'backend' => { 'name' => 'test-backend', 'type' => 'test' } })

    expect(result).not_to be_nil
  end

  it 'register_post_processor_trait_bridge: register_post_processor: trait bridge' do
    result = Kreuzberg.register_post_processor({ 'processor' => { 'name' => 'test-processor', 'type' => 'test' } })

    expect(result).not_to be_nil
  end

  it 'register_renderer_trait_bridge: register_renderer: trait bridge' do
    result = Kreuzberg.register_renderer({ 'renderer' => { 'name' => 'test-renderer', 'type' => 'test' } })

    expect(result).not_to be_nil
  end

  it 'register_validator_trait_bridge: register_validator: trait bridge' do
    result = Kreuzberg.register_validator({ 'validator' => { 'name' => 'test-validator', 'type' => 'test' } })

    expect(result).not_to be_nil
  end

  it 'unregister_document_extractor_after_register: unregister_document_extractor' do
    result = Kreuzberg.unregister_document_extractor('test-extractor')

    expect(result).not_to be_nil
  end

  it 'unregister_embedding_backend_after_register: unregister_embedding_backend' do
    result = Kreuzberg.unregister_embedding_backend('test-embedding-backend')

    expect(result).not_to be_nil
  end

  it 'unregister_post_processor_after_register: unregister_post_processor' do
    result = Kreuzberg.unregister_post_processor('test-processor')

    expect(result).not_to be_nil
  end

  it 'unregister_renderer_after_register: unregister_renderer' do
    result = Kreuzberg.unregister_renderer('test-renderer')

    expect(result).not_to be_nil
  end

  it 'unregister_validator_after_register: unregister_validator' do
    result = Kreuzberg.unregister_validator('test-validator')

    expect(result).not_to be_nil
  end
end
