# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7a2af3f1ee1f82b2d25b0ab58aebf48a036e634c41c91eeb08f2251b75b35b35
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'registry' do
  it 'list_document_extractors: List document extractors' do
    result = Kreuzberg.list_document_extractors()

    expect(result).not_to be_nil
  end

  it 'list_embedding_backends: List embedding backends' do
    result = Kreuzberg.list_embedding_backends()

    expect(result).not_to be_nil
  end

  it 'list_ocr_backends: List OCR backends' do
    result = Kreuzberg.list_ocr_backends()

    expect(result).not_to be_nil
  end

  it 'list_post_processors: List post-processors' do
    result = Kreuzberg.list_post_processors()

    expect(result).not_to be_nil
  end

  it 'list_renderers: List renderers' do
    result = Kreuzberg.list_renderers()

    expect(result).not_to be_nil
  end

  it 'list_validators: List validators' do
    result = Kreuzberg.list_validators()

    expect(result).not_to be_nil
  end
end
