# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a4b2535e507ad7d6891f9f696c62001bdc930272512ef1c9e8e151cb54027e5f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'registry_operations' do
  it 'extensions_docx: Get file extensions for DOCX MIME type' do
    result = Kreuzberg.get_extensions_for_mime('application/vnd.openxmlformats-officedocument.wordprocessingml.document')

    expect(result).not_to be_nil
  end

  it 'extensions_html: Get file extensions for HTML MIME type' do
    result = Kreuzberg.get_extensions_for_mime('text/html')

    expect(result).not_to be_nil
  end

  it 'extensions_pdf: Get file extensions for PDF MIME type' do
    result = Kreuzberg.get_extensions_for_mime('application/pdf')

    expect(result).not_to be_nil
  end
end
