// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:726a3fd39cf66cd2bb8d93d438522b35c25092ad762bd643f2d46ecb5811c55e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// ignore_for_file: unused_local_variable

import 'package:test/test.dart';
import 'package:kreuzberg/kreuzberg.dart';
import 'package:kreuzberg/src/kreuzberg_bridge_generated/frb_generated.dart' show RustLib;

// E2e tests for category: document_extractor_management
void main() {
  setUpAll(() async {
    await RustLib.init();
  });

  test('Clear all document extractors and verify list is empty', () async {
    final result = await KreuzbergBridge.clearDocumentExtractors();
    expect(result, anyOf(isNull, isEmpty));
  });

  test('List all registered document extractors', () async {
    final result = await KreuzbergBridge.listDocumentExtractors();
  });

}
