// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ddf3e53c4879c7f4db64fbd395ab06fb5d74f57527f0ed75d73bdf047628777a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// ignore_for_file: unused_local_variable

import 'package:test/test.dart';
import 'package:kreuzberg/kreuzberg.dart';
import 'package:kreuzberg/src/kreuzberg_bridge_generated/frb_generated.dart' show RustLib;

// E2e tests for category: ocr_backend_management
void main() {
  setUpAll(() async {
    await RustLib.init();
  });

  test('Clear all OCR backends and verify list is empty', () async {
    final result = await KreuzbergBridge.clearOcrBackends();
    expect(result, anyOf(isNull, isEmpty));
  });

  test('List all registered OCR backends', () async {
    final result = await KreuzbergBridge.listOcrBackends();
  });

  test('Unregister nonexistent OCR backend gracefully', () async {
    final result = await KreuzbergBridge.unregisterOcrBackend('nonexistent-backend-xyz');
  });

}
