// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0426c63c510288bc5c017d3ac67bbb41f59a864840f686760b5bee87d57d26b5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// ignore_for_file: unused_local_variable

import 'package:test/test.dart';
import 'package:kreuzberg/kreuzberg.dart';
import 'package:kreuzberg/src/kreuzberg_bridge_generated/frb_generated.dart' show RustLib;

// E2e tests for category: post_processor_management
void main() {
  setUpAll(() async {
    await RustLib.init();
  });

  test('Clear all post-processors and verify list is empty', () async {
    final result = await KreuzbergBridge.clearPostProcessors();
  });

  test('List all registered post-processors', () async {
    final result = await KreuzbergBridge.listPostProcessors();
  });

}
