// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:79774bcea4dc3ac24212ce45535e1836f117ba9743da0dbe415cff34c778ea2b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// ignore_for_file: unused_local_variable

import 'package:test/test.dart';
import 'package:kreuzberg/kreuzberg.dart';
import 'package:kreuzberg/src/kreuzberg_bridge_generated/frb_generated.dart' show RustLib;

// E2e tests for category: registry_operations
void main() {
  setUpAll(() async {
    await RustLib.init();
  });

  test('Get file extensions for DOCX MIME type', () async {
    final result = await KreuzbergBridge.getExtensionsForMime('application/vnd.openxmlformats-officedocument.wordprocessingml.document');
  });

  test('Get file extensions for HTML MIME type', () async {
    final result = await KreuzbergBridge.getExtensionsForMime('text/html');
  });

  test('Get file extensions for PDF MIME type', () async {
    final result = await KreuzbergBridge.getExtensionsForMime('application/pdf');
    expect(result, contains('pdf'));
  });

}
