// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:35b120c3d65e74d9abb4e44846aa2b7d0b3dae7901ccac07cfec9528d60824aa
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// ignore_for_file: unused_local_variable

import 'package:test/test.dart';
import 'package:kreuzberg/kreuzberg.dart';
import 'package:kreuzberg/src/kreuzberg_bridge_generated/frb_generated.dart' show RustLib;

// E2e tests for category: renderer_management
void main() {
  setUpAll(() async {
    await RustLib.init();
  });

  test('Clear all renderers and verify list is empty', () async {
    final result = await KreuzbergBridge.clearRenderers();
    expect(result, anyOf(isNull, isEmpty));
  });

  test('List all registered renderers', () async {
    final result = await KreuzbergBridge.listRenderers();
  });

}
