// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: embed_extra
package e2e_test

import (
	"encoding/json"
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_EmbedTextsBatch(t *testing.T) {
	// Batch embed texts
	var texts []string
	if err := json.Unmarshal([]byte(`["hello","world"]`), &texts); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	var config kreuzberg.EmbeddingConfig
	if err := json.Unmarshal([]byte(`{"model":{"name":"balanced","type":"preset"}}`), &config); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	_, err := kreuzberg.EmbedTextsAsync(texts, config)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
