// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: ocr_backend_management
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_OcrBackendsClear(t *testing.T) {
	// Clear all OCR backends and verify list is empty
	_ = kreuzberg.ClearOcrBackends()
}

func Test_OcrBackendsList(t *testing.T) {
	// List all registered OCR backends
	_, err := kreuzberg.ListOcrBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OcrBackendsUnregister(t *testing.T) {
	// Unregister nonexistent OCR backend gracefully
	_ = kreuzberg.UnregisterOcrBackend(`nonexistent-backend-xyz`)
}
