// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c7381e76b869830dfced254e472e0eb0e507f99a4720b1db461ac1d90abd519a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: plugin_api
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_RegisterDocumentExtractorTraitBridge(t *testing.T) {
	// register_document_extractor: trait bridge
	err := kreuzberg.RegisterDocumentExtractor()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_RegisterEmbeddingBackendTraitBridge(t *testing.T) {
	// register_embedding_backend: trait bridge
	err := kreuzberg.RegisterEmbeddingBackend()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_RegisterOcrBackendTraitBridge(t *testing.T) {
	// register_ocr_backend: trait bridge
	err := kreuzberg.RegisterOcrBackend()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_RegisterPostProcessorTraitBridge(t *testing.T) {
	// register_post_processor: trait bridge
	err := kreuzberg.RegisterPostProcessor()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_RegisterRendererTraitBridge(t *testing.T) {
	// register_renderer: trait bridge
	err := kreuzberg.RegisterRenderer()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_RegisterValidatorTraitBridge(t *testing.T) {
	// register_validator: trait bridge
	err := kreuzberg.RegisterValidator()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_UnregisterDocumentExtractorAfterRegister(t *testing.T) {
	// unregister_document_extractor
	err := kreuzberg.UnregisterDocumentExtractor(`test-extractor`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_UnregisterEmbeddingBackendAfterRegister(t *testing.T) {
	// unregister_embedding_backend
	err := kreuzberg.UnregisterEmbeddingBackend(`test-embedding-backend`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_UnregisterPostProcessorAfterRegister(t *testing.T) {
	// unregister_post_processor
	err := kreuzberg.UnregisterPostProcessor(`test-processor`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_UnregisterRendererAfterRegister(t *testing.T) {
	// unregister_renderer
	err := kreuzberg.UnregisterRenderer(`test-renderer`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_UnregisterValidatorAfterRegister(t *testing.T) {
	// unregister_validator
	err := kreuzberg.UnregisterValidator(`test-validator`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
