// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a4b2535e507ad7d6891f9f696c62001bdc930272512ef1c9e8e151cb54027e5f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: registry_operations
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_ExtensionsDocx(t *testing.T) {
	// Get file extensions for DOCX MIME type
	_, err := kreuzberg.GetExtensionsForMime(`application/vnd.openxmlformats-officedocument.wordprocessingml.document`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ExtensionsHtml(t *testing.T) {
	// Get file extensions for HTML MIME type
	_, err := kreuzberg.GetExtensionsForMime(`text/html`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ExtensionsPdf(t *testing.T) {
	// Get file extensions for PDF MIME type
	_, err := kreuzberg.GetExtensionsForMime(`application/pdf`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
