// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2ff29038011095afb3d7eb8a09db81e45782cb56105ffc3ad1d768578b86fa35
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: validator_management
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_ValidatorsClear(t *testing.T) {
	// Clear all validators and verify list is empty
	_ = kreuzberg.ClearValidators()
}

func Test_ValidatorsList(t *testing.T) {
	// List all registered validators
	_, err := kreuzberg.ListValidators()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
