// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7a2af3f1ee1f82b2d25b0ab58aebf48a036e634c41c91eeb08f2251b75b35b35
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import dev.kreuzberg.ExtractionConfig

/** E2e tests for category: code. */
class CodeTest {

    companion object {
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).registerKotlinModule().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testCodeShebangDetection() = runBlocking {
        // Test language detection from shebang line via bytes input
        val result = Kreuzberg.extractFileSync("code/script.sh", "text/x-source-code", ExtractionConfig())
        assertEquals("text/x-source-code", result.mimeType.trim())
        assertTrue(result.content.length >= 10, "expected length >= 10")
        assertTrue(result.content.contains("build"), "expected to contain: " + "build")
        assertTrue(result.content.contains("clean"), "expected to contain: " + "clean")
    }

}
