// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7a2af3f1ee1f82b2d25b0ab58aebf48a036e634c41c91eeb08f2251b75b35b35
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import dev.kreuzberg.EmbeddingConfig

/** E2e tests for category: embed_async_pending. */
class EmbedAsyncPendingTest {

    companion object {
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).registerKotlinModule().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testEmbedTextsAsyncEmptyInput() = runBlocking {
        // embed_texts_async: empty text list
        val result = Kreuzberg.embedTextsAsync(listOf(), EmbeddingConfig())
        // skipped: field 'embeddings' not available on result type
    }

    @Test
    fun testEmbedTextsAsyncHappy() = runBlocking {
        // embed_texts_async: basic async embedding
        val result = Kreuzberg.embedTextsAsync(listOf("First", "Second"), EmbeddingConfig())
        // skipped: field 'embeddings' not available on result type
    }

    @Test
    fun testEmbedTextsAsyncPresetSwitch() = runBlocking {
        // embed_texts_async: preset override
        val config = MAPPER.readValue("{\"model\":{\"name\":\"balanced\",\"type\":\"preset\"}}", EmbeddingConfig::class.java)
        val result = Kreuzberg.embedTextsAsync(listOf("Text"), config)
    }

}
