// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6497a5e387ca93240d8355b5f0fd27673529850ead82056bbb7c3be7d9c36f49
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg
import dev.kreuzberg.EmbeddingBackendBridge

/** E2e tests for category: embedding_backend_management. */
class EmbeddingBackendManagementTest {
    @Test
    fun testEmbeddingBackendsClear() = runBlocking {
        // Clear all embedding backends and verify list is empty
        val result = EmbeddingBackendBridge.clearAll()
    }

    @Test
    fun testEmbeddingBackendsList() = runBlocking {
        // List all registered embedding backends
        val result = Kreuzberg.listEmbeddingBackends()
    }

}
