// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2ff29038011095afb3d7eb8a09db81e45782cb56105ffc3ad1d768578b86fa35
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg

/** E2e tests for category: post_processor_management. */
class PostProcessorManagementTest {
    @Test
    fun testPostProcessorsClear() = runBlocking {
        // Clear all post-processors and verify list is empty
        val result = PostProcessorBridge.clearAll()
    }

    @Test
    fun testPostProcessorsList() = runBlocking {
        // List all registered post-processors
        val result = Kreuzberg.listPostProcessors()
    }

}
