// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7a2af3f1ee1f82b2d25b0ab58aebf48a036e634c41c91eeb08f2251b75b35b35
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg

/** E2e tests for category: registry_operations. */
class RegistryOperationsTest {
    @Test
    fun testExtensionsDocx() = runBlocking {
        // Get file extensions for DOCX MIME type
        val result = Kreuzberg.getExtensionsForMime("application/vnd.openxmlformats-officedocument.wordprocessingml.document")
    }

    @Test
    fun testExtensionsHtml() = runBlocking {
        // Get file extensions for HTML MIME type
        val result = Kreuzberg.getExtensionsForMime("text/html")
    }

    @Test
    fun testExtensionsPdf() = runBlocking {
        // Get file extensions for PDF MIME type
        val result = Kreuzberg.getExtensionsForMime("application/pdf")
    }

}
