// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8b5acbcd2bff197415c9a137e65758c2cc03c3693d15c120e66ee37b38d4232f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg

/** E2e tests for category: renderer_management. */
class RendererManagementTest {
    @Test
    fun testRenderersList() = runBlocking {
        // List all registered renderers
        val result = Kreuzberg.listRenderers()
    }

}
